package com.wckj.chasstage.modules.jqxx.entity;

import java.util.Date;

public class ChasYwJqxx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.id
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqbh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqmc
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqdd
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjmj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String cjmj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjmj_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String cjmjSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjdw
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String cjdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjdw_dm
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String cjdwDm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjnr
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String cjnr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqly
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqlyms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqlyms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqlb
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqlbms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqlbms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqzt
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jqztms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jqztms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jbrxm
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jbrxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.jbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String jbrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.bjsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date bjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.bjdh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String bjdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.pdddsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date pdddsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.pdjssj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date pdjssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.ddxcsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date ddxcsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjcs
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String cjcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjjg
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String cjjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.cjyj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String cjyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.lrr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.lrsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.xgr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.xgsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.org_sys_code
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String orgSysCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.isdel
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.data_flag
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String dataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.sjbq
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date sjbq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.shzt
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private String shzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.sftx
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Integer sftx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_jqxx.shsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    private Date shsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.id
     *
     * @return the value of chas_yw_jqxx.id
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.id
     *
     * @param id the value for chas_yw_jqxx.id
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqbh
     *
     * @return the value of chas_yw_jqxx.jqbh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqbh() {
        return jqbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqbh
     *
     * @param jqbh the value for chas_yw_jqxx.jqbh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqbh(String jqbh) {
        this.jqbh = jqbh == null ? null : jqbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqmc
     *
     * @return the value of chas_yw_jqxx.jqmc
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqmc() {
        return jqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqmc
     *
     * @param jqmc the value for chas_yw_jqxx.jqmc
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqmc(String jqmc) {
        this.jqmc = jqmc == null ? null : jqmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqdd
     *
     * @return the value of chas_yw_jqxx.jqdd
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqdd() {
        return jqdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqdd
     *
     * @param jqdd the value for chas_yw_jqxx.jqdd
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqdd(String jqdd) {
        this.jqdd = jqdd == null ? null : jqdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjmj
     *
     * @return the value of chas_yw_jqxx.cjmj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getCjmj() {
        return cjmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjmj
     *
     * @param cjmj the value for chas_yw_jqxx.cjmj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjmj(String cjmj) {
        this.cjmj = cjmj == null ? null : cjmj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjmj_sfzh
     *
     * @return the value of chas_yw_jqxx.cjmj_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getCjmjSfzh() {
        return cjmjSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjmj_sfzh
     *
     * @param cjmjSfzh the value for chas_yw_jqxx.cjmj_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjmjSfzh(String cjmjSfzh) {
        this.cjmjSfzh = cjmjSfzh == null ? null : cjmjSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjdw
     *
     * @return the value of chas_yw_jqxx.cjdw
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getCjdw() {
        return cjdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjdw
     *
     * @param cjdw the value for chas_yw_jqxx.cjdw
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjdw(String cjdw) {
        this.cjdw = cjdw == null ? null : cjdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjdw_dm
     *
     * @return the value of chas_yw_jqxx.cjdw_dm
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getCjdwDm() {
        return cjdwDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjdw_dm
     *
     * @param cjdwDm the value for chas_yw_jqxx.cjdw_dm
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjdwDm(String cjdwDm) {
        this.cjdwDm = cjdwDm == null ? null : cjdwDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjnr
     *
     * @return the value of chas_yw_jqxx.cjnr
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getCjnr() {
        return cjnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjnr
     *
     * @param cjnr the value for chas_yw_jqxx.cjnr
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjnr(String cjnr) {
        this.cjnr = cjnr == null ? null : cjnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjsj
     *
     * @return the value of chas_yw_jqxx.cjsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjsj
     *
     * @param cjsj the value for chas_yw_jqxx.cjsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqly
     *
     * @return the value of chas_yw_jqxx.jqly
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqly() {
        return jqly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqly
     *
     * @param jqly the value for chas_yw_jqxx.jqly
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqly(String jqly) {
        this.jqly = jqly == null ? null : jqly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqlyms
     *
     * @return the value of chas_yw_jqxx.jqlyms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqlyms() {
        return jqlyms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqlyms
     *
     * @param jqlyms the value for chas_yw_jqxx.jqlyms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqlyms(String jqlyms) {
        this.jqlyms = jqlyms == null ? null : jqlyms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqlb
     *
     * @return the value of chas_yw_jqxx.jqlb
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqlb() {
        return jqlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqlb
     *
     * @param jqlb the value for chas_yw_jqxx.jqlb
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqlb(String jqlb) {
        this.jqlb = jqlb == null ? null : jqlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqlbms
     *
     * @return the value of chas_yw_jqxx.jqlbms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqlbms() {
        return jqlbms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqlbms
     *
     * @param jqlbms the value for chas_yw_jqxx.jqlbms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqlbms(String jqlbms) {
        this.jqlbms = jqlbms == null ? null : jqlbms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqzt
     *
     * @return the value of chas_yw_jqxx.jqzt
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqzt() {
        return jqzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqzt
     *
     * @param jqzt the value for chas_yw_jqxx.jqzt
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqzt(String jqzt) {
        this.jqzt = jqzt == null ? null : jqzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jqztms
     *
     * @return the value of chas_yw_jqxx.jqztms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJqztms() {
        return jqztms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jqztms
     *
     * @param jqztms the value for chas_yw_jqxx.jqztms
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJqztms(String jqztms) {
        this.jqztms = jqztms == null ? null : jqztms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jbrxm
     *
     * @return the value of chas_yw_jqxx.jbrxm
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJbrxm() {
        return jbrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jbrxm
     *
     * @param jbrxm the value for chas_yw_jqxx.jbrxm
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJbrxm(String jbrxm) {
        this.jbrxm = jbrxm == null ? null : jbrxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.jbr_sfzh
     *
     * @return the value of chas_yw_jqxx.jbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getJbrSfzh() {
        return jbrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.jbr_sfzh
     *
     * @param jbrSfzh the value for chas_yw_jqxx.jbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setJbrSfzh(String jbrSfzh) {
        this.jbrSfzh = jbrSfzh == null ? null : jbrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.bjsj
     *
     * @return the value of chas_yw_jqxx.bjsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getBjsj() {
        return bjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.bjsj
     *
     * @param bjsj the value for chas_yw_jqxx.bjsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setBjsj(Date bjsj) {
        this.bjsj = bjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.bjdh
     *
     * @return the value of chas_yw_jqxx.bjdh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getBjdh() {
        return bjdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.bjdh
     *
     * @param bjdh the value for chas_yw_jqxx.bjdh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setBjdh(String bjdh) {
        this.bjdh = bjdh == null ? null : bjdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.pdddsj
     *
     * @return the value of chas_yw_jqxx.pdddsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getPdddsj() {
        return pdddsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.pdddsj
     *
     * @param pdddsj the value for chas_yw_jqxx.pdddsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setPdddsj(Date pdddsj) {
        this.pdddsj = pdddsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.pdjssj
     *
     * @return the value of chas_yw_jqxx.pdjssj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getPdjssj() {
        return pdjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.pdjssj
     *
     * @param pdjssj the value for chas_yw_jqxx.pdjssj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setPdjssj(Date pdjssj) {
        this.pdjssj = pdjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.ddxcsj
     *
     * @return the value of chas_yw_jqxx.ddxcsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getDdxcsj() {
        return ddxcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.ddxcsj
     *
     * @param ddxcsj the value for chas_yw_jqxx.ddxcsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setDdxcsj(Date ddxcsj) {
        this.ddxcsj = ddxcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjcs
     *
     * @return the value of chas_yw_jqxx.cjcs
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getCjcs() {
        return cjcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjcs
     *
     * @param cjcs the value for chas_yw_jqxx.cjcs
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjcs(String cjcs) {
        this.cjcs = cjcs == null ? null : cjcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjjg
     *
     * @return the value of chas_yw_jqxx.cjjg
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getCjjg() {
        return cjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjjg
     *
     * @param cjjg the value for chas_yw_jqxx.cjjg
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjjg(String cjjg) {
        this.cjjg = cjjg == null ? null : cjjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.cjyj
     *
     * @return the value of chas_yw_jqxx.cjyj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getCjyj() {
        return cjyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.cjyj
     *
     * @param cjyj the value for chas_yw_jqxx.cjyj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setCjyj(String cjyj) {
        this.cjyj = cjyj == null ? null : cjyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.lrr_sfzh
     *
     * @return the value of chas_yw_jqxx.lrr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.lrr_sfzh
     *
     * @param lrrSfzh the value for chas_yw_jqxx.lrr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.lrsj
     *
     * @return the value of chas_yw_jqxx.lrsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.lrsj
     *
     * @param lrsj the value for chas_yw_jqxx.lrsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.xgr_sfzh
     *
     * @return the value of chas_yw_jqxx.xgr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.xgr_sfzh
     *
     * @param xgrSfzh the value for chas_yw_jqxx.xgr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.xgsj
     *
     * @return the value of chas_yw_jqxx.xgsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.xgsj
     *
     * @param xgsj the value for chas_yw_jqxx.xgsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.org_sys_code
     *
     * @return the value of chas_yw_jqxx.org_sys_code
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getOrgSysCode() {
        return orgSysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.org_sys_code
     *
     * @param orgSysCode the value for chas_yw_jqxx.org_sys_code
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setOrgSysCode(String orgSysCode) {
        this.orgSysCode = orgSysCode == null ? null : orgSysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.isdel
     *
     * @return the value of chas_yw_jqxx.isdel
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.isdel
     *
     * @param isdel the value for chas_yw_jqxx.isdel
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.data_flag
     *
     * @return the value of chas_yw_jqxx.data_flag
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.data_flag
     *
     * @param dataFlag the value for chas_yw_jqxx.data_flag
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.sjbq
     *
     * @return the value of chas_yw_jqxx.sjbq
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getSjbq() {
        return sjbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.sjbq
     *
     * @param sjbq the value for chas_yw_jqxx.sjbq
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setSjbq(Date sjbq) {
        this.sjbq = sjbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.shzt
     *
     * @return the value of chas_yw_jqxx.shzt
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public String getShzt() {
        return shzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.shzt
     *
     * @param shzt the value for chas_yw_jqxx.shzt
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setShzt(String shzt) {
        this.shzt = shzt == null ? null : shzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.sftx
     *
     * @return the value of chas_yw_jqxx.sftx
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Integer getSftx() {
        return sftx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.sftx
     *
     * @param sftx the value for chas_yw_jqxx.sftx
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setSftx(Integer sftx) {
        this.sftx = sftx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_jqxx.shsj
     *
     * @return the value of chas_yw_jqxx.shsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public Date getShsj() {
        return shsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_jqxx.shsj
     *
     * @param shsj the value for chas_yw_jqxx.shsj
     *
     * @mbg.generated Wed Jul 31 16:35:29 CST 2019
     */
    public void setShsj(Date shsj) {
        this.shsj = shsj;
    }
}