package com.wckj.chasstage.modules.sswp.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ChasSswpxx implements java.io.Serializable{
	/**
	 *
	 */
	private static final long serialVersionUID = 7755256350570269297L;

	/**
	 *
	 */
	private String id;

	/**
	 *
	 */
	private Integer isdel;

	/**
	 *
	 */
	private String dataflag;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.LRR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String lrrSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.LRSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private Date lrsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.XGR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String xgrSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.XGSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private Date xgsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.baqid
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String baqid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.BAQMC
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String baqmc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.WPBH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String wpbh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.CLLX
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String cllx;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.LX
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String lx;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.MC
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String mc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.LB
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String lb;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.CYR
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String cyr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.DW
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String dw;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.SL
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String sl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.TZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String tz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.JZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private BigDecimal jz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.CFWZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String cfwz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.TXM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String txm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.BZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String bz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.WPZT
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String wpzt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.ZBR_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String zbrXm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.ZBR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String zbrSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.ZBDW_BH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String zbdwBh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.TBSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private Date tbsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.RKSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private Date rksj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.CKSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private Date cksj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.RKMJ_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String rkmjSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.RKMJ_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String rkmjXm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.CKMJ_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String ckmjSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.CKMJ_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String ckmjXm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.RYBH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private String rybh;

	private String wjid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_sswpxx.EWM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	private byte[] ewm;

	private String dwxtbh;
	private Integer sfznbaq;
	/**用于存放物品照片*/
	private String bizId;
	private String wpclzt;
	/**用户委托邮寄的的邮寄单号和邮寄照片id*/
	private String yjdh;
	private String yjzpid;

	public ChasSswpxx() {
		this.isdel = 0;
		this.dataflag = "0";
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.ID
	 *
	 * @return the value of gg_sswpxx.ID
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.ID
	 *
	 * @param id
	 *            the value for gg_sswpxx.ID
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	public String getDwxtbh() {
		return dwxtbh;
	}

	public void setDwxtbh(String dwxtbh) {
		this.dwxtbh = dwxtbh == null ? null : dwxtbh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.ISDEL
	 *
	 * @return the value of gg_sswpxx.ISDEL
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public Integer getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.ISDEL
	 *
	 * @param isdel
	 *            the value for gg_sswpxx.ISDEL
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.dataflag
	 *
	 * @return the value of gg_sswpxx.dataflag
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getDataflag() {
		return dataflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.dataflag
	 *
	 * @param dataflag
	 *            the value for gg_sswpxx.dataflag
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setDataflag(String dataflag) {
		this.dataflag = dataflag == null ? null : dataflag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.LRR_SFZH
	 *
	 * @return the value of gg_sswpxx.LRR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getLrrSfzh() {
		return lrrSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.LRR_SFZH
	 *
	 * @param lrrSfzh
	 *            the value for gg_sswpxx.LRR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setLrrSfzh(String lrrSfzh) {
		this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.LRSJ
	 *
	 * @return the value of gg_sswpxx.LRSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public Date getLrsj() {
		return lrsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.LRSJ
	 *
	 * @param lrsj
	 *            the value for gg_sswpxx.LRSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setLrsj(Date lrsj) {
		this.lrsj = lrsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.XGR_SFZH
	 *
	 * @return the value of gg_sswpxx.XGR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getXgrSfzh() {
		return xgrSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.XGR_SFZH
	 *
	 * @param xgrSfzh
	 *            the value for gg_sswpxx.XGR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setXgrSfzh(String xgrSfzh) {
		this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.XGSJ
	 *
	 * @return the value of gg_sswpxx.XGSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public Date getXgsj() {
		return xgsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.XGSJ
	 *
	 * @param xgsj
	 *            the value for gg_sswpxx.XGSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setXgsj(Date xgsj) {
		this.xgsj = xgsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.baqid
	 *
	 * @return the value of gg_sswpxx.baqid
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getBaqid() {
		return baqid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.baqid
	 *
	 * @param baqid
	 *            the value for gg_sswpxx.baqid
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setBaqid(String baqid) {
		this.baqid = baqid == null ? null : baqid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.BAQMC
	 *
	 * @return the value of gg_sswpxx.BAQMC
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getBaqmc() {
		return baqmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.BAQMC
	 *
	 * @param baqmc
	 *            the value for gg_sswpxx.BAQMC
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setBaqmc(String baqmc) {
		this.baqmc = baqmc == null ? null : baqmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.WPBH
	 *
	 * @return the value of gg_sswpxx.WPBH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getWpbh() {
		return wpbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.WPBH
	 *
	 * @param wpbh
	 *            the value for gg_sswpxx.WPBH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setWpbh(String wpbh) {
		this.wpbh = wpbh == null ? null : wpbh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.CLLX
	 *
	 * @return the value of gg_sswpxx.CLLX
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getCllx() {
		return cllx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.CLLX
	 *
	 * @param cllx
	 *            the value for gg_sswpxx.CLLX
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setCllx(String cllx) {
		this.cllx = cllx == null ? null : cllx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.LX
	 *
	 * @return the value of gg_sswpxx.LX
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getLx() {
		return lx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.LX
	 *
	 * @param lx
	 *            the value for gg_sswpxx.LX
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setLx(String lx) {
		this.lx = lx == null ? null : lx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.MC
	 *
	 * @return the value of gg_sswpxx.MC
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getMc() {
		return mc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.MC
	 *
	 * @param mc
	 *            the value for gg_sswpxx.MC
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setMc(String mc) {
		this.mc = mc == null ? null : mc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.LB
	 *
	 * @return the value of gg_sswpxx.LB
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getLb() {
		return lb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.LB
	 *
	 * @param lb
	 *            the value for gg_sswpxx.LB
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setLb(String lb) {
		this.lb = lb == null ? null : lb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.CYR
	 *
	 * @return the value of gg_sswpxx.CYR
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getCyr() {
		return cyr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.CYR
	 *
	 * @param cyr
	 *            the value for gg_sswpxx.CYR
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setCyr(String cyr) {
		this.cyr = cyr == null ? null : cyr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.DW
	 *
	 * @return the value of gg_sswpxx.DW
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getDw() {
		return dw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.DW
	 *
	 * @param dw
	 *            the value for gg_sswpxx.DW
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setDw(String dw) {
		this.dw = dw == null ? null : dw.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.SL
	 *
	 * @return the value of gg_sswpxx.SL
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getSl() {
		return sl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.SL
	 *
	 * @param sl
	 *            the value for gg_sswpxx.SL
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setSl(String sl) {
		this.sl = sl == null ? null : sl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.TZ
	 *
	 * @return the value of gg_sswpxx.TZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getTz() {
		return tz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.TZ
	 *
	 * @param tz
	 *            the value for gg_sswpxx.TZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setTz(String tz) {
		this.tz = tz == null ? null : tz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.JZ
	 *
	 * @return the value of gg_sswpxx.JZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public BigDecimal getJz() {
		return jz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.JZ
	 *
	 * @param jz
	 *            the value for gg_sswpxx.JZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setJz(BigDecimal jz) {
		this.jz = jz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.CFWZ
	 *
	 * @return the value of gg_sswpxx.CFWZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getCfwz() {
		return cfwz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.CFWZ
	 *
	 * @param cfwz
	 *            the value for gg_sswpxx.CFWZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setCfwz(String cfwz) {
		this.cfwz = cfwz == null ? null : cfwz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.TXM
	 *
	 * @return the value of gg_sswpxx.TXM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getTxm() {
		return txm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.TXM
	 *
	 * @param txm
	 *            the value for gg_sswpxx.TXM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setTxm(String txm) {
		this.txm = txm == null ? null : txm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.BZ
	 *
	 * @return the value of gg_sswpxx.BZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getBz() {
		return bz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.BZ
	 *
	 * @param bz
	 *            the value for gg_sswpxx.BZ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setBz(String bz) {
		this.bz = bz == null ? null : bz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.WPZT
	 *
	 * @return the value of gg_sswpxx.WPZT
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getWpzt() {
		return wpzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.WPZT
	 *
	 * @param wpzt
	 *            the value for gg_sswpxx.WPZT
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setWpzt(String wpzt) {
		this.wpzt = wpzt == null ? null : wpzt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.ZBR_XM
	 *
	 * @return the value of gg_sswpxx.ZBR_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getZbrXm() {
		return zbrXm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.ZBR_XM
	 *
	 * @param zbrXm
	 *            the value for gg_sswpxx.ZBR_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setZbrXm(String zbrXm) {
		this.zbrXm = zbrXm == null ? null : zbrXm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.ZBR_SFZH
	 *
	 * @return the value of gg_sswpxx.ZBR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getZbrSfzh() {
		return zbrSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.ZBR_SFZH
	 *
	 * @param zbrSfzh
	 *            the value for gg_sswpxx.ZBR_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setZbrSfzh(String zbrSfzh) {
		this.zbrSfzh = zbrSfzh == null ? null : zbrSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.ZBDW_BH
	 *
	 * @return the value of gg_sswpxx.ZBDW_BH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getZbdwBh() {
		return zbdwBh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.ZBDW_BH
	 *
	 * @param zbdwBh
	 *            the value for gg_sswpxx.ZBDW_BH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setZbdwBh(String zbdwBh) {
		this.zbdwBh = zbdwBh == null ? null : zbdwBh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.TBSJ
	 *
	 * @return the value of gg_sswpxx.TBSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public Date getTbsj() {
		return tbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.TBSJ
	 *
	 * @param tbsj
	 *            the value for gg_sswpxx.TBSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setTbsj(Date tbsj) {
		this.tbsj = tbsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.RKSJ
	 *
	 * @return the value of gg_sswpxx.RKSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public Date getRksj() {
		return rksj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.RKSJ
	 *
	 * @param rksj
	 *            the value for gg_sswpxx.RKSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setRksj(Date rksj) {
		this.rksj = rksj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.CKSJ
	 *
	 * @return the value of gg_sswpxx.CKSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public Date getCksj() {
		return cksj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.CKSJ
	 *
	 * @param cksj
	 *            the value for gg_sswpxx.CKSJ
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setCksj(Date cksj) {
		this.cksj = cksj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.RKMJ_SFZH
	 *
	 * @return the value of gg_sswpxx.RKMJ_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getRkmjSfzh() {
		return rkmjSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.RKMJ_SFZH
	 *
	 * @param rkmjSfzh
	 *            the value for gg_sswpxx.RKMJ_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setRkmjSfzh(String rkmjSfzh) {
		this.rkmjSfzh = rkmjSfzh == null ? null : rkmjSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.RKMJ_XM
	 *
	 * @return the value of gg_sswpxx.RKMJ_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getRkmjXm() {
		return rkmjXm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.RKMJ_XM
	 *
	 * @param rkmjXm
	 *            the value for gg_sswpxx.RKMJ_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setRkmjXm(String rkmjXm) {
		this.rkmjXm = rkmjXm == null ? null : rkmjXm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.CKMJ_SFZH
	 *
	 * @return the value of gg_sswpxx.CKMJ_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getCkmjSfzh() {
		return ckmjSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.CKMJ_SFZH
	 *
	 * @param ckmjSfzh
	 *            the value for gg_sswpxx.CKMJ_SFZH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setCkmjSfzh(String ckmjSfzh) {
		this.ckmjSfzh = ckmjSfzh == null ? null : ckmjSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.CKMJ_XM
	 *
	 * @return the value of gg_sswpxx.CKMJ_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getCkmjXm() {
		return ckmjXm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.CKMJ_XM
	 *
	 * @param ckmjXm
	 *            the value for gg_sswpxx.CKMJ_XM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setCkmjXm(String ckmjXm) {
		this.ckmjXm = ckmjXm == null ? null : ckmjXm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.RYBH
	 *
	 * @return the value of gg_sswpxx.RYBH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public String getRybh() {
		return rybh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.RYBH
	 *
	 * @param rybh
	 *            the value for gg_sswpxx.RYBH
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setRybh(String rybh) {
		this.rybh = rybh == null ? null : rybh.trim();
	}

	public String getWjid() {
		return wjid;
	}

	public void setWjid(String wjid) {
		this.wjid = wjid == null ? null : wjid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_sswpxx.EWM
	 *
	 * @return the value of gg_sswpxx.EWM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public byte[] getEwm() {
		return ewm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_sswpxx.EWM
	 *
	 * @param ewm
	 *            the value for gg_sswpxx.EWM
	 *
	 * @mbg.generated Tue Nov 21 18:09:54 CST 2017
	 */
	public void setEwm(byte[] ewm) {
		this.ewm = ewm;
	}

	public Integer getSfznbaq() {
		return sfznbaq;
	}

	public void setSfznbaq(Integer sfznbaq) {
		this.sfznbaq = sfznbaq;
	}

    public String getWpclzt() {
        return wpclzt;
    }

    public void setWpclzt(String wpclzt) {
        this.wpclzt = wpclzt;
    }

	public String getYjdh() { return yjdh; }

	public void setYjdh(String yjdh) { this.yjdh = yjdh; }

	public String getYjzpid() {	return yjzpid; }

	public void setYjzpid(String yjzpid) { this.yjzpid = yjzpid; }
}
