package com.wckj.chasstage.api.def.yybb.model;

import com.wckj.chasstage.modules.baq.entity.ChasBaq;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;


/**
 * @author wutl
 * @Title: 语音播报参数
 * @Package
 * @Description:
 * @date 2020-12-2216:02
 */
public class YybbParam {
    @ApiModelProperty("主键")
    private String id;
    @ApiModelProperty("办案区id")
    private String baqid;
    @ApiModelProperty("播报环节,字典CHASSTAGE_YYBBSJ")
    private String bbhj;
    @ApiModelProperty("播报内容")
    private String bbnr;
    @ApiModelProperty("办案区名称")
    private String baqmc;
    @ApiModelProperty("是否启用 1是0否")
    private Integer sfqy;
    @ApiModelProperty("区域id")
    private String qyid;
    @ApiModelProperty("区域名称")
    private String qymc;
    @ApiModelProperty(value = "办案区Id集合",hidden = true)
    private List<ChasBaq> baqidList;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getBaqid() {
        return baqid;
    }

    public void setBaqid(String baqid) {
        this.baqid = baqid == null ? null : baqid.trim();
    }

    public String getBbhj() {
        return bbhj;
    }

    public void setBbhj(String bbhj) {
        this.bbhj = bbhj;
    }

    public String getBbnr() {
        return bbnr;
    }

    public void setBbnr(String bbnr) {
        this.bbnr = bbnr == null ? null : bbnr.trim();
    }


    public String getBaqmc() {
        return baqmc;
    }

    public void setBaqmc(String baqmc) {
        this.baqmc = baqmc == null ? null : baqmc.trim();
    }

    public Integer getSfqy() {
        return sfqy;
    }

    public void setSfqy(Integer sfqy) {
        this.sfqy = sfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.qyid
     *
     * @return the value of chas_yw_yybb.qyid
     *
     * @mbg.generated Tue Dec 22 19:01:42 CST 2020
     */
    public String getQyid() {
        return qyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.qyid
     *
     * @param qyid the value for chas_yw_yybb.qyid
     *
     * @mbg.generated Tue Dec 22 19:01:42 CST 2020
     */
    public void setQyid(String qyid) {
        this.qyid = qyid == null ? null : qyid.trim();
    }

    public String getQymc() {
        return qymc;
    }

    public void setQymc(String qymc) {
        this.qymc = qymc;
    }

    public List<ChasBaq> getBaqidList() {
        return baqidList;
    }

    public void setBaqidList(List<ChasBaq> baqidList) {
        this.baqidList = baqidList;
    }
}
