package com.wckj.chasstage.modules.ajxx.entity;

import java.util.Date;

public class ChasYwAjxx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.id
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajbh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajmc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.zbr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String zbrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.zbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String zbrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.xbr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String xbrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.xbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String xbrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.zbdw_dm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String zbdwDm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.zbdw_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String zbdwMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.org_sys_code
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String orgSysCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajzt
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajzt_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajztMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajlx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajlx_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajlxMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajlb
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajlb_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajlbMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.jyaq
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String jyaq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.isdel
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.sfzb
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String sfzb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ay_bh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ayBh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ay_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ayMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.fadd
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String fadd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.fasj_sx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date fasjSx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.fasj_xx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date fasjXx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.bjsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date bjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.slsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date slsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.lasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date lasj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.pasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date pasj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.jasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date jasj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.bylasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date bylasj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.cxajsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date cxajsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.ajly
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String ajly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.lrsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.lrr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.lrr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String lrrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.xgsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.xgr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.xgr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String xgrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.lapzsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date lapzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.lapzr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String lapzrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.lapzr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String lapzrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.data_flag
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String dataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.sjbq
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Date sjbq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.shzt
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private String shzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_ajxx.sftx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    private Integer sftx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.id
     *
     * @return the value of chas_yw_ajxx.id
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.id
     *
     * @param id the value for chas_yw_ajxx.id
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajbh
     *
     * @return the value of chas_yw_ajxx.ajbh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjbh() {
        return ajbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajbh
     *
     * @param ajbh the value for chas_yw_ajxx.ajbh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjbh(String ajbh) {
        this.ajbh = ajbh == null ? null : ajbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajmc
     *
     * @return the value of chas_yw_ajxx.ajmc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjmc() {
        return ajmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajmc
     *
     * @param ajmc the value for chas_yw_ajxx.ajmc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjmc(String ajmc) {
        this.ajmc = ajmc == null ? null : ajmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.zbr_xm
     *
     * @return the value of chas_yw_ajxx.zbr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getZbrXm() {
        return zbrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.zbr_xm
     *
     * @param zbrXm the value for chas_yw_ajxx.zbr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setZbrXm(String zbrXm) {
        this.zbrXm = zbrXm == null ? null : zbrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.zbr_sfzh
     *
     * @return the value of chas_yw_ajxx.zbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getZbrSfzh() {
        return zbrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.zbr_sfzh
     *
     * @param zbrSfzh the value for chas_yw_ajxx.zbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setZbrSfzh(String zbrSfzh) {
        this.zbrSfzh = zbrSfzh == null ? null : zbrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.xbr_xm
     *
     * @return the value of chas_yw_ajxx.xbr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getXbrXm() {
        return xbrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.xbr_xm
     *
     * @param xbrXm the value for chas_yw_ajxx.xbr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setXbrXm(String xbrXm) {
        this.xbrXm = xbrXm == null ? null : xbrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.xbr_sfzh
     *
     * @return the value of chas_yw_ajxx.xbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getXbrSfzh() {
        return xbrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.xbr_sfzh
     *
     * @param xbrSfzh the value for chas_yw_ajxx.xbr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setXbrSfzh(String xbrSfzh) {
        this.xbrSfzh = xbrSfzh == null ? null : xbrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.zbdw_dm
     *
     * @return the value of chas_yw_ajxx.zbdw_dm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getZbdwDm() {
        return zbdwDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.zbdw_dm
     *
     * @param zbdwDm the value for chas_yw_ajxx.zbdw_dm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setZbdwDm(String zbdwDm) {
        this.zbdwDm = zbdwDm == null ? null : zbdwDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.zbdw_mc
     *
     * @return the value of chas_yw_ajxx.zbdw_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getZbdwMc() {
        return zbdwMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.zbdw_mc
     *
     * @param zbdwMc the value for chas_yw_ajxx.zbdw_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setZbdwMc(String zbdwMc) {
        this.zbdwMc = zbdwMc == null ? null : zbdwMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.org_sys_code
     *
     * @return the value of chas_yw_ajxx.org_sys_code
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getOrgSysCode() {
        return orgSysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.org_sys_code
     *
     * @param orgSysCode the value for chas_yw_ajxx.org_sys_code
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setOrgSysCode(String orgSysCode) {
        this.orgSysCode = orgSysCode == null ? null : orgSysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajzt
     *
     * @return the value of chas_yw_ajxx.ajzt
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjzt() {
        return ajzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajzt
     *
     * @param ajzt the value for chas_yw_ajxx.ajzt
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjzt(String ajzt) {
        this.ajzt = ajzt == null ? null : ajzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajzt_mc
     *
     * @return the value of chas_yw_ajxx.ajzt_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjztMc() {
        return ajztMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajzt_mc
     *
     * @param ajztMc the value for chas_yw_ajxx.ajzt_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjztMc(String ajztMc) {
        this.ajztMc = ajztMc == null ? null : ajztMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajlx
     *
     * @return the value of chas_yw_ajxx.ajlx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjlx() {
        return ajlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajlx
     *
     * @param ajlx the value for chas_yw_ajxx.ajlx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjlx(String ajlx) {
        this.ajlx = ajlx == null ? null : ajlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajlx_mc
     *
     * @return the value of chas_yw_ajxx.ajlx_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjlxMc() {
        return ajlxMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajlx_mc
     *
     * @param ajlxMc the value for chas_yw_ajxx.ajlx_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjlxMc(String ajlxMc) {
        this.ajlxMc = ajlxMc == null ? null : ajlxMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajlb
     *
     * @return the value of chas_yw_ajxx.ajlb
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjlb() {
        return ajlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajlb
     *
     * @param ajlb the value for chas_yw_ajxx.ajlb
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjlb(String ajlb) {
        this.ajlb = ajlb == null ? null : ajlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajlb_mc
     *
     * @return the value of chas_yw_ajxx.ajlb_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjlbMc() {
        return ajlbMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajlb_mc
     *
     * @param ajlbMc the value for chas_yw_ajxx.ajlb_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjlbMc(String ajlbMc) {
        this.ajlbMc = ajlbMc == null ? null : ajlbMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.jyaq
     *
     * @return the value of chas_yw_ajxx.jyaq
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getJyaq() {
        return jyaq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.jyaq
     *
     * @param jyaq the value for chas_yw_ajxx.jyaq
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setJyaq(String jyaq) {
        this.jyaq = jyaq == null ? null : jyaq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.isdel
     *
     * @return the value of chas_yw_ajxx.isdel
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.isdel
     *
     * @param isdel the value for chas_yw_ajxx.isdel
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.sfzb
     *
     * @return the value of chas_yw_ajxx.sfzb
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getSfzb() {
        return sfzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.sfzb
     *
     * @param sfzb the value for chas_yw_ajxx.sfzb
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setSfzb(String sfzb) {
        this.sfzb = sfzb == null ? null : sfzb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ay_bh
     *
     * @return the value of chas_yw_ajxx.ay_bh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAyBh() {
        return ayBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ay_bh
     *
     * @param ayBh the value for chas_yw_ajxx.ay_bh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAyBh(String ayBh) {
        this.ayBh = ayBh == null ? null : ayBh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ay_mc
     *
     * @return the value of chas_yw_ajxx.ay_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAyMc() {
        return ayMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ay_mc
     *
     * @param ayMc the value for chas_yw_ajxx.ay_mc
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAyMc(String ayMc) {
        this.ayMc = ayMc == null ? null : ayMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.fadd
     *
     * @return the value of chas_yw_ajxx.fadd
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getFadd() {
        return fadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.fadd
     *
     * @param fadd the value for chas_yw_ajxx.fadd
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setFadd(String fadd) {
        this.fadd = fadd == null ? null : fadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.fasj_sx
     *
     * @return the value of chas_yw_ajxx.fasj_sx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getFasjSx() {
        return fasjSx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.fasj_sx
     *
     * @param fasjSx the value for chas_yw_ajxx.fasj_sx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setFasjSx(Date fasjSx) {
        this.fasjSx = fasjSx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.fasj_xx
     *
     * @return the value of chas_yw_ajxx.fasj_xx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getFasjXx() {
        return fasjXx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.fasj_xx
     *
     * @param fasjXx the value for chas_yw_ajxx.fasj_xx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setFasjXx(Date fasjXx) {
        this.fasjXx = fasjXx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.bjsj
     *
     * @return the value of chas_yw_ajxx.bjsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getBjsj() {
        return bjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.bjsj
     *
     * @param bjsj the value for chas_yw_ajxx.bjsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setBjsj(Date bjsj) {
        this.bjsj = bjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.slsj
     *
     * @return the value of chas_yw_ajxx.slsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getSlsj() {
        return slsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.slsj
     *
     * @param slsj the value for chas_yw_ajxx.slsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setSlsj(Date slsj) {
        this.slsj = slsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.lasj
     *
     * @return the value of chas_yw_ajxx.lasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getLasj() {
        return lasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.lasj
     *
     * @param lasj the value for chas_yw_ajxx.lasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setLasj(Date lasj) {
        this.lasj = lasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.pasj
     *
     * @return the value of chas_yw_ajxx.pasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getPasj() {
        return pasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.pasj
     *
     * @param pasj the value for chas_yw_ajxx.pasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setPasj(Date pasj) {
        this.pasj = pasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.jasj
     *
     * @return the value of chas_yw_ajxx.jasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getJasj() {
        return jasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.jasj
     *
     * @param jasj the value for chas_yw_ajxx.jasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setJasj(Date jasj) {
        this.jasj = jasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.bylasj
     *
     * @return the value of chas_yw_ajxx.bylasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getBylasj() {
        return bylasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.bylasj
     *
     * @param bylasj the value for chas_yw_ajxx.bylasj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setBylasj(Date bylasj) {
        this.bylasj = bylasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.cxajsj
     *
     * @return the value of chas_yw_ajxx.cxajsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getCxajsj() {
        return cxajsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.cxajsj
     *
     * @param cxajsj the value for chas_yw_ajxx.cxajsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setCxajsj(Date cxajsj) {
        this.cxajsj = cxajsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.ajly
     *
     * @return the value of chas_yw_ajxx.ajly
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getAjly() {
        return ajly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.ajly
     *
     * @param ajly the value for chas_yw_ajxx.ajly
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setAjly(String ajly) {
        this.ajly = ajly == null ? null : ajly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.lrsj
     *
     * @return the value of chas_yw_ajxx.lrsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.lrsj
     *
     * @param lrsj the value for chas_yw_ajxx.lrsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.lrr_sfzh
     *
     * @return the value of chas_yw_ajxx.lrr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.lrr_sfzh
     *
     * @param lrrSfzh the value for chas_yw_ajxx.lrr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.lrr_xm
     *
     * @return the value of chas_yw_ajxx.lrr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getLrrXm() {
        return lrrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.lrr_xm
     *
     * @param lrrXm the value for chas_yw_ajxx.lrr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setLrrXm(String lrrXm) {
        this.lrrXm = lrrXm == null ? null : lrrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.xgsj
     *
     * @return the value of chas_yw_ajxx.xgsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.xgsj
     *
     * @param xgsj the value for chas_yw_ajxx.xgsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.xgr_sfzh
     *
     * @return the value of chas_yw_ajxx.xgr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.xgr_sfzh
     *
     * @param xgrSfzh the value for chas_yw_ajxx.xgr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.xgr_xm
     *
     * @return the value of chas_yw_ajxx.xgr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getXgrXm() {
        return xgrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.xgr_xm
     *
     * @param xgrXm the value for chas_yw_ajxx.xgr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setXgrXm(String xgrXm) {
        this.xgrXm = xgrXm == null ? null : xgrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.lapzsj
     *
     * @return the value of chas_yw_ajxx.lapzsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getLapzsj() {
        return lapzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.lapzsj
     *
     * @param lapzsj the value for chas_yw_ajxx.lapzsj
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setLapzsj(Date lapzsj) {
        this.lapzsj = lapzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.lapzr_sfzh
     *
     * @return the value of chas_yw_ajxx.lapzr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getLapzrSfzh() {
        return lapzrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.lapzr_sfzh
     *
     * @param lapzrSfzh the value for chas_yw_ajxx.lapzr_sfzh
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setLapzrSfzh(String lapzrSfzh) {
        this.lapzrSfzh = lapzrSfzh == null ? null : lapzrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.lapzr_xm
     *
     * @return the value of chas_yw_ajxx.lapzr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getLapzrXm() {
        return lapzrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.lapzr_xm
     *
     * @param lapzrXm the value for chas_yw_ajxx.lapzr_xm
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setLapzrXm(String lapzrXm) {
        this.lapzrXm = lapzrXm == null ? null : lapzrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.data_flag
     *
     * @return the value of chas_yw_ajxx.data_flag
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.data_flag
     *
     * @param dataFlag the value for chas_yw_ajxx.data_flag
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.sjbq
     *
     * @return the value of chas_yw_ajxx.sjbq
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Date getSjbq() {
        return sjbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.sjbq
     *
     * @param sjbq the value for chas_yw_ajxx.sjbq
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setSjbq(Date sjbq) {
        this.sjbq = sjbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.shzt
     *
     * @return the value of chas_yw_ajxx.shzt
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public String getShzt() {
        return shzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.shzt
     *
     * @param shzt the value for chas_yw_ajxx.shzt
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setShzt(String shzt) {
        this.shzt = shzt == null ? null : shzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_ajxx.sftx
     *
     * @return the value of chas_yw_ajxx.sftx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public Integer getSftx() {
        return sftx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_ajxx.sftx
     *
     * @param sftx the value for chas_yw_ajxx.sftx
     *
     * @mbg.generated Wed Jul 31 16:36:08 CST 2019
     */
    public void setSftx(Integer sftx) {
        this.sftx = sftx;
    }
}