package com.wckj.chasstage.modules.tjdj.entity;

public class ChasTjdj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_tjdj.id
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_tjdj.ryid
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    private String ryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_tjdj.rstj
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    private String rstj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_tjdj.xbzw
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    private String xbzw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_tjdj.bcjc
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    private String bcjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_tjdj.xdt
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    private String xdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_tjdj.xcg
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    private String xcg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_tjdj.xyjc
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    private String xyjc;

    private String qt;

    private Integer sfyc;

    private String ycsm;

    private String rybh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_tjdj.id
     *
     * @return the value of gg_tjdj.id
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_tjdj.id
     *
     * @param id the value for gg_tjdj.id
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_tjdj.ryid
     *
     * @return the value of gg_tjdj.ryid
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public String getRyid() {
        return ryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_tjdj.ryid
     *
     * @param ryid the value for gg_tjdj.ryid
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public void setRyid(String ryid) {
        this.ryid = ryid == null ? null : ryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_tjdj.rstj
     *
     * @return the value of gg_tjdj.rstj
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public String getRstj() {
        return rstj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_tjdj.rstj
     *
     * @param rstj the value for gg_tjdj.rstj
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public void setRstj(String rstj) {
        this.rstj = rstj == null ? null : rstj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_tjdj.xbzw
     *
     * @return the value of gg_tjdj.xbzw
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public String getXbzw() {
        return xbzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_tjdj.xbzw
     *
     * @param xbzw the value for gg_tjdj.xbzw
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public void setXbzw(String xbzw) {
        this.xbzw = xbzw == null ? null : xbzw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_tjdj.bcjc
     *
     * @return the value of gg_tjdj.bcjc
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public String getBcjc() {
        return bcjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_tjdj.bcjc
     *
     * @param bcjc the value for gg_tjdj.bcjc
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public void setBcjc(String bcjc) {
        this.bcjc = bcjc == null ? null : bcjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_tjdj.xdt
     *
     * @return the value of gg_tjdj.xdt
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public String getXdt() {
        return xdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_tjdj.xdt
     *
     * @param xdt the value for gg_tjdj.xdt
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public void setXdt(String xdt) {
        this.xdt = xdt == null ? null : xdt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_tjdj.xcg
     *
     * @return the value of gg_tjdj.xcg
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public String getXcg() {
        return xcg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_tjdj.xcg
     *
     * @param xcg the value for gg_tjdj.xcg
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public void setXcg(String xcg) {
        this.xcg = xcg == null ? null : xcg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_tjdj.xyjc
     *
     * @return the value of gg_tjdj.xyjc
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public String getXyjc() {
        return xyjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_tjdj.xyjc
     *
     * @param xyjc the value for gg_tjdj.xyjc
     *
     * @mbg.generated Sat May 09 14:32:54 CST 2020
     */
    public void setXyjc(String xyjc) {
        this.xyjc = xyjc == null ? null : xyjc.trim();
    }

    public String getQt() {
        return qt;
    }

    public void setQt(String qt) {
        this.qt = qt;
    }

    public Integer getSfyc() {
        return sfyc;
    }

    public void setSfyc(Integer sfyc) {
        this.sfyc = sfyc;
    }

    public String getYcsm() {
        return ycsm;
    }

    public void setYcsm(String ycsm) {
        this.ycsm = ycsm;
    }

    public String getRybh() {
        return rybh;
    }

    public void setRybh(String rybh) {
        this.rybh = rybh;
    }
}
