package com.wckj.chasstage.modules.qysljcjl.dao;

import com.wckj.chasstage.modules.qygl.entity.ChasXtQy;
import com.wckj.chasstage.modules.qysljcjl.entity.ChasYwQysljcjl;
import com.wckj.framework.orm.mybatis.dao.IBaseDao;
import com.wckj.framework.orm.mybatis.data.set.MybatisPageDataResultSet;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ChasYwQysljcjlMapper extends IBaseDao<ChasYwQysljcjl> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chas_yw_qysljcjl
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chas_yw_qysljcjl
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    int insert(ChasYwQysljcjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chas_yw_qysljcjl
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    ChasYwQysljcjl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chas_yw_qysljcjl
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    List<ChasYwQysljcjl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chas_yw_qysljcjl
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    int updateByPrimaryKey(ChasYwQysljcjl record);

    int leaveRecordsBasedOnZoneId(@Param("qyid")String qyid);

    MybatisPageDataResultSet<Map<String,Object>> getEntityPageDataNew(@Param("pageNo") int var1, @Param("pageSize") int var2, @Param("param") Object var3, @Param("orderBy") String var4);
}