package com.wckj.chasstage.modules.qysljcjl.entity;

import java.util.Date;

public class ChasYwQysljcjl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.id
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.isdel
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private Short isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.data_flag
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String dataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.lrr_sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.lrsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.xgr_sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.xgsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.baqid
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String baqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.baqmc
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String baqmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.dwdm
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String dwdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.dwxtbh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String dwxtbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.zt
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String zt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.rylx
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String rylx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.qylx
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String qylx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.qyid
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String qyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.qymc
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String qymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.czr
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String czr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.czsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private Date czsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.ryxm
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String ryxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.rybh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String rybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.sjbq
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private Date sjbq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.jrsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private Date jrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.lksj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private Date lksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String sfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_qysljcjl.khdip
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    private String khdip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.id
     *
     * @return the value of chas_yw_qysljcjl.id
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.id
     *
     * @param id the value for chas_yw_qysljcjl.id
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.isdel
     *
     * @return the value of chas_yw_qysljcjl.isdel
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public Short getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.isdel
     *
     * @param isdel the value for chas_yw_qysljcjl.isdel
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setIsdel(Short isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.data_flag
     *
     * @return the value of chas_yw_qysljcjl.data_flag
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.data_flag
     *
     * @param dataFlag the value for chas_yw_qysljcjl.data_flag
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.lrr_sfzh
     *
     * @return the value of chas_yw_qysljcjl.lrr_sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.lrr_sfzh
     *
     * @param lrrSfzh the value for chas_yw_qysljcjl.lrr_sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.lrsj
     *
     * @return the value of chas_yw_qysljcjl.lrsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.lrsj
     *
     * @param lrsj the value for chas_yw_qysljcjl.lrsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.xgr_sfzh
     *
     * @return the value of chas_yw_qysljcjl.xgr_sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.xgr_sfzh
     *
     * @param xgrSfzh the value for chas_yw_qysljcjl.xgr_sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.xgsj
     *
     * @return the value of chas_yw_qysljcjl.xgsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.xgsj
     *
     * @param xgsj the value for chas_yw_qysljcjl.xgsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.baqid
     *
     * @return the value of chas_yw_qysljcjl.baqid
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getBaqid() {
        return baqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.baqid
     *
     * @param baqid the value for chas_yw_qysljcjl.baqid
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setBaqid(String baqid) {
        this.baqid = baqid == null ? null : baqid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.baqmc
     *
     * @return the value of chas_yw_qysljcjl.baqmc
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getBaqmc() {
        return baqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.baqmc
     *
     * @param baqmc the value for chas_yw_qysljcjl.baqmc
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setBaqmc(String baqmc) {
        this.baqmc = baqmc == null ? null : baqmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.dwdm
     *
     * @return the value of chas_yw_qysljcjl.dwdm
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getDwdm() {
        return dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.dwdm
     *
     * @param dwdm the value for chas_yw_qysljcjl.dwdm
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setDwdm(String dwdm) {
        this.dwdm = dwdm == null ? null : dwdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.dwxtbh
     *
     * @return the value of chas_yw_qysljcjl.dwxtbh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getDwxtbh() {
        return dwxtbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.dwxtbh
     *
     * @param dwxtbh the value for chas_yw_qysljcjl.dwxtbh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setDwxtbh(String dwxtbh) {
        this.dwxtbh = dwxtbh == null ? null : dwxtbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.zt
     *
     * @return the value of chas_yw_qysljcjl.zt
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.zt
     *
     * @param zt the value for chas_yw_qysljcjl.zt
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.rylx
     *
     * @return the value of chas_yw_qysljcjl.rylx
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getRylx() {
        return rylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.rylx
     *
     * @param rylx the value for chas_yw_qysljcjl.rylx
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setRylx(String rylx) {
        this.rylx = rylx == null ? null : rylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.qylx
     *
     * @return the value of chas_yw_qysljcjl.qylx
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getQylx() {
        return qylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.qylx
     *
     * @param qylx the value for chas_yw_qysljcjl.qylx
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setQylx(String qylx) {
        this.qylx = qylx == null ? null : qylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.qyid
     *
     * @return the value of chas_yw_qysljcjl.qyid
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getQyid() {
        return qyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.qyid
     *
     * @param qyid the value for chas_yw_qysljcjl.qyid
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setQyid(String qyid) {
        this.qyid = qyid == null ? null : qyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.qymc
     *
     * @return the value of chas_yw_qysljcjl.qymc
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getQymc() {
        return qymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.qymc
     *
     * @param qymc the value for chas_yw_qysljcjl.qymc
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setQymc(String qymc) {
        this.qymc = qymc == null ? null : qymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.czr
     *
     * @return the value of chas_yw_qysljcjl.czr
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getCzr() {
        return czr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.czr
     *
     * @param czr the value for chas_yw_qysljcjl.czr
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setCzr(String czr) {
        this.czr = czr == null ? null : czr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.czsj
     *
     * @return the value of chas_yw_qysljcjl.czsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.czsj
     *
     * @param czsj the value for chas_yw_qysljcjl.czsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.ryxm
     *
     * @return the value of chas_yw_qysljcjl.ryxm
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getRyxm() {
        return ryxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.ryxm
     *
     * @param ryxm the value for chas_yw_qysljcjl.ryxm
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setRyxm(String ryxm) {
        this.ryxm = ryxm == null ? null : ryxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.rybh
     *
     * @return the value of chas_yw_qysljcjl.rybh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getRybh() {
        return rybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.rybh
     *
     * @param rybh the value for chas_yw_qysljcjl.rybh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setRybh(String rybh) {
        this.rybh = rybh == null ? null : rybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.sjbq
     *
     * @return the value of chas_yw_qysljcjl.sjbq
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public Date getSjbq() {
        return sjbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.sjbq
     *
     * @param sjbq the value for chas_yw_qysljcjl.sjbq
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setSjbq(Date sjbq) {
        this.sjbq = sjbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.jrsj
     *
     * @return the value of chas_yw_qysljcjl.jrsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public Date getJrsj() {
        return jrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.jrsj
     *
     * @param jrsj the value for chas_yw_qysljcjl.jrsj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setJrsj(Date jrsj) {
        this.jrsj = jrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.lksj
     *
     * @return the value of chas_yw_qysljcjl.lksj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public Date getLksj() {
        return lksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.lksj
     *
     * @param lksj the value for chas_yw_qysljcjl.lksj
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setLksj(Date lksj) {
        this.lksj = lksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.sfzh
     *
     * @return the value of chas_yw_qysljcjl.sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.sfzh
     *
     * @param sfzh the value for chas_yw_qysljcjl.sfzh
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_qysljcjl.khdip
     *
     * @return the value of chas_yw_qysljcjl.khdip
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public String getKhdip() {
        return khdip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_qysljcjl.khdip
     *
     * @param khdip the value for chas_yw_qysljcjl.khdip
     *
     * @mbg.generated Thu Nov 09 13:31:05 CST 2023
     */
    public void setKhdip(String khdip) {
        this.khdip = khdip == null ? null : khdip.trim();
    }
}