package com.wckj.chasstage.modules.ythcj.entity;

import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.redis.serializer.JdkSerializationRedisSerializer;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class ChasYthcj extends JdkSerializationRedisSerializer implements java.io.Serializable {
	/**
     * 
     */
	private static final long serialVersionUID = -1494480862405105701L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ID
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("id")
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ISDEL
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("是否逻辑删除")
	private Integer isdel;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.dataflag
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("数据版本号不必上传")
	private String dataflag;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LRR_SFZH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("录入人身份证")
	private String lrrSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LRSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("录入时间")
	private Date lrsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XGR_SFZH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("修改人身份证")
	private String xgrSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XGSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("修改时间")
	private Date xgsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.baqid
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("办案区ID")
	private String baqid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.BAQMC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("办案区名称")
	private String baqmc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.RYBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("人员编号")
	private String rybh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("人员姓名")
	private String ryxm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.RYSFZH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("人员身份证")
	private String rysfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XB
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("性别")
	private String xb;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.CSRQ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("出生日期 年月日")
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date csrq;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.BM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("别名")
	private String bm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.CYM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("曾用名")
	private String cym;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.WWXM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("外文姓名")
	private String wwxm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.GJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("国籍")
	private String gj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.WHCD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("文化程度")
	private String whcd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.MZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("民族")
	private String mz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.JG
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("籍贯")
	private String jg;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZZMM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("政治面貌")
	private String zzmm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.SF
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("身份")
	private String sf;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.QTZJLX1
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("其他证件类型1")
	private String qtzjlx1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.QTZJHM1
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("其他证件号码1")
	private String qtzjhm1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.GZDW
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("工作单位")
	private String gzdw;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.HJD_XZQH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("户籍地行政区划")
	private String hjdxzqh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.HJDXZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("户籍地详细地址")
	private String hjdxz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.HJDPCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("户籍地派出所")
	private String hjdpcs;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XZD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("现住地")
	private String xzd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XZDXZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("现住地详细地址")
	private String xzdxz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XZDXZ_X
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("现住地详细地址X坐标")
	private String xzdxzX;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XZDXZ_Y
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("现住地详细地址Y坐标")
	private String xzdxzY;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XZDPCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("现住地派出所")
	private String xzdpcs;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XZSQ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("现住社区")
	private String xzsq;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LJQH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("落脚区划")
	private String ljqh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LJDMC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("落脚地名称")
	private String ljdmc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LJTD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("落脚特点")
	private String ljtd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LJCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("落脚时间")
	private String ljcs;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LJBW
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("落脚部位")
	private String ljbw;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.JZSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("居住时间")
	private String jzsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.SG
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("身高")
	private String sg;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体重")
	private String tz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("足长")
	private String zc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.XX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("血型")
	private String xx;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("脸型")
	private String lx;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体型")
	private String tx;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZHC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("专长")
	private String zhc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TBBJ11
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体表标记11")
	private String tbbj11;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TBBJ12
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体表标记12")
	private String tbbj12;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TBBJ13
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体表标记13")
	private String tbbj13;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TBBJ14
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体表标记14")
	private String tbbj14;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TSTZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("特殊体征")
	private String tstz;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TBBJ21
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体表标记21")
	private String tbbj21;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TBBJ22
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体表标记22")
	private String tbbj22;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TBBJ23
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体表标记23")
	private String tbbj23;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.TBBJ24
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("体表标记24")
	private String tbbj24;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZWBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("指纹编号")
	private String zwbh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.DNABH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("dna编号")
	private String dnabh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZJBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("足迹编号")
	private String zjbh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.LXDH2
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("联系电话2")
	private String lxdh2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.RYZP
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("人员照片")
	private String ryzp;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.SDQK
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("涉毒情况")
	private String sdqk;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.DJQK
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("毒检情况")
	private String djqk;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZBDW_BH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("主办单位编号")
	private String zbdwBh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZBDW_MC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("主办单位名称")
	private String zbdwMc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.RYLX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("人员类型")
	private String rylx;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZMZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("正面照片路径")
	private String zmzpPath;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.ZCZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("左侧照片路径")
	private String zczpPath;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.YCZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("右侧照片路径")
	private String yczpPath;
	@ApiModelProperty("联系电话1")
	private String lxdh1;
	@ApiModelProperty("单位系统编号")
	private String dwxtbh;
	@ApiModelProperty("区域编号")
	private String qybh;
	@ApiModelProperty("区域名称")
	private String qymc;
	@ApiModelProperty("毛发情况(00:未检测,01已检测)")
	private String mfqk;
	
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.RYZP_ZM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("人员照片正面")
	private byte[] ryzpZm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.RYZP_ZC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("人员照片左侧")
	private byte[] ryzpZc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gg_ythcj_ryxx.RYZP_YC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	@ApiModelProperty("人员照片右侧")
	private byte[] ryzpYc;

	@ApiModelProperty("正面照片base64")
	private String ryzpZmBase64;
	@ApiModelProperty("左侧照片base64")
	private String ryzpZcBase64;
	@ApiModelProperty("右侧照片base64")
	private String ryzpYcBase64;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ID
	 *
	 * @return the value of gg_ythcj_ryxx.ID
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ID
	 *
	 * @param id
	 *            the value for gg_ythcj_ryxx.ID
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ISDEL
	 *
	 * @return the value of gg_ythcj_ryxx.ISDEL
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public Integer getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ISDEL
	 *
	 * @param isdel
	 *            the value for gg_ythcj_ryxx.ISDEL
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}
	public String getLxdh1() {
		return lxdh1;
	}

	public void setLxdh1(String lxdh1) {
		this.lxdh1 = lxdh1 == null ? null : lxdh1.trim();
	}

	public String getDwxtbh() {
		return dwxtbh;
	}

	public void setDwxtbh(String dwxtbh) {
		this.dwxtbh = dwxtbh == null ? null : dwxtbh.trim();
	}

	public String getQybh() {
		return qybh;
	}

	public void setQybh(String qybh) {
		this.qybh = qybh == null ? null : qybh.trim();
	}

	public String getQymc() {
		return qymc;
	}

	public void setQymc(String qymc) {
		this.qymc = qymc == null ? null : qymc.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.dataflag
	 *
	 * @return the value of gg_ythcj_ryxx.dataflag
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getDataflag() {
		return dataflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.dataflag
	 *
	 * @param dataflag
	 *            the value for gg_ythcj_ryxx.dataflag
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setDataflag(String dataflag) {
		this.dataflag = dataflag == null ? null : dataflag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LRR_SFZH
	 *
	 * @return the value of gg_ythcj_ryxx.LRR_SFZH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getLrrSfzh() {
		return lrrSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LRR_SFZH
	 *
	 * @param lrrSfzh
	 *            the value for gg_ythcj_ryxx.LRR_SFZH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLrrSfzh(String lrrSfzh) {
		this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LRSJ
	 *
	 * @return the value of gg_ythcj_ryxx.LRSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public Date getLrsj() {
		return lrsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LRSJ
	 *
	 * @param lrsj
	 *            the value for gg_ythcj_ryxx.LRSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLrsj(Date lrsj) {
		this.lrsj = lrsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XGR_SFZH
	 *
	 * @return the value of gg_ythcj_ryxx.XGR_SFZH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXgrSfzh() {
		return xgrSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XGR_SFZH
	 *
	 * @param xgrSfzh
	 *            the value for gg_ythcj_ryxx.XGR_SFZH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXgrSfzh(String xgrSfzh) {
		this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XGSJ
	 *
	 * @return the value of gg_ythcj_ryxx.XGSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public Date getXgsj() {
		return xgsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XGSJ
	 *
	 * @param xgsj
	 *            the value for gg_ythcj_ryxx.XGSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXgsj(Date xgsj) {
		this.xgsj = xgsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.baqid
	 *
	 * @return the value of gg_ythcj_ryxx.baqid
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getBaqid() {
		return baqid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.baqid
	 *
	 * @param baqid
	 *            the value for gg_ythcj_ryxx.baqid
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setBaqid(String baqid) {
		this.baqid = baqid == null ? null : baqid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.BAQMC
	 *
	 * @return the value of gg_ythcj_ryxx.BAQMC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getBaqmc() {
		return baqmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.BAQMC
	 *
	 * @param baqmc
	 *            the value for gg_ythcj_ryxx.BAQMC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setBaqmc(String baqmc) {
		this.baqmc = baqmc == null ? null : baqmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.RYBH
	 *
	 * @return the value of gg_ythcj_ryxx.RYBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getRybh() {
		return rybh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.RYBH
	 *
	 * @param rybh
	 *            the value for gg_ythcj_ryxx.RYBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setRybh(String rybh) {
		this.rybh = rybh == null ? null : rybh.trim();
	}

	public String getRyxm() {
		return ryxm;
	}

	public void setRyxm(String ryxm) {
		this.ryxm = ryxm == null ? null : ryxm.trim();
	}

	public String getRysfzh() {
		return rysfzh;
	}

	public void setRysfzh(String rysfzh) {
		this.rysfzh = rysfzh == null ? null : rysfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XB
	 *
	 * @return the value of gg_ythcj_ryxx.XB
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXb() {
		return xb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XB
	 *
	 * @param xb
	 *            the value for gg_ythcj_ryxx.XB
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXb(String xb) {
		this.xb = xb == null ? null : xb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.CSRQ
	 *
	 * @return the value of gg_ythcj_ryxx.CSRQ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public Date getCsrq() {
		return csrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.CSRQ
	 *
	 * @param csrq
	 *            the value for gg_ythcj_ryxx.CSRQ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setCsrq(Date csrq) {
		this.csrq = csrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.BM
	 *
	 * @return the value of gg_ythcj_ryxx.BM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getBm() {
		return bm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.BM
	 *
	 * @param bm
	 *            the value for gg_ythcj_ryxx.BM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setBm(String bm) {
		this.bm = bm == null ? null : bm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.CYM
	 *
	 * @return the value of gg_ythcj_ryxx.CYM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getCym() {
		return cym;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.CYM
	 *
	 * @param cym
	 *            the value for gg_ythcj_ryxx.CYM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setCym(String cym) {
		this.cym = cym == null ? null : cym.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.WWXM
	 *
	 * @return the value of gg_ythcj_ryxx.WWXM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getWwxm() {
		return wwxm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.WWXM
	 *
	 * @param wwxm
	 *            the value for gg_ythcj_ryxx.WWXM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setWwxm(String wwxm) {
		this.wwxm = wwxm == null ? null : wwxm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.GJ
	 *
	 * @return the value of gg_ythcj_ryxx.GJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getGj() {
		return gj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.GJ
	 *
	 * @param gj
	 *            the value for gg_ythcj_ryxx.GJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setGj(String gj) {
		this.gj = gj == null ? null : gj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.WHCD
	 *
	 * @return the value of gg_ythcj_ryxx.WHCD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getWhcd() {
		return whcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.WHCD
	 *
	 * @param whcd
	 *            the value for gg_ythcj_ryxx.WHCD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setWhcd(String whcd) {
		this.whcd = whcd == null ? null : whcd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.MZ
	 *
	 * @return the value of gg_ythcj_ryxx.MZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getMz() {
		return mz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.MZ
	 *
	 * @param mz
	 *            the value for gg_ythcj_ryxx.MZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setMz(String mz) {
		this.mz = mz == null ? null : mz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.JG
	 *
	 * @return the value of gg_ythcj_ryxx.JG
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getJg() {
		return jg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.JG
	 *
	 * @param jg
	 *            the value for gg_ythcj_ryxx.JG
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setJg(String jg) {
		this.jg = jg == null ? null : jg.trim();
	}

	public String getZzmm() {
		return zzmm;
	}

	public void setZzmm(String zzmm) {
		this.zzmm = zzmm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.SF
	 *
	 * @return the value of gg_ythcj_ryxx.SF
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getSf() {
		return sf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.SF
	 *
	 * @param sf
	 *            the value for gg_ythcj_ryxx.SF
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setSf(String sf) {
		this.sf = sf == null ? null : sf.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.QTZJLX1
	 *
	 * @return the value of gg_ythcj_ryxx.QTZJLX1
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getQtzjlx1() {
		return qtzjlx1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.QTZJLX1
	 *
	 * @param qtzjlx1
	 *            the value for gg_ythcj_ryxx.QTZJLX1
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setQtzjlx1(String qtzjlx1) {
		this.qtzjlx1 = qtzjlx1 == null ? null : qtzjlx1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.QTZJHM1
	 *
	 * @return the value of gg_ythcj_ryxx.QTZJHM1
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getQtzjhm1() {
		return qtzjhm1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.QTZJHM1
	 *
	 * @param qtzjhm1
	 *            the value for gg_ythcj_ryxx.QTZJHM1
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setQtzjhm1(String qtzjhm1) {
		this.qtzjhm1 = qtzjhm1 == null ? null : qtzjhm1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.GZDW
	 *
	 * @return the value of gg_ythcj_ryxx.GZDW
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getGzdw() {
		return gzdw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.GZDW
	 *
	 * @param gzdw
	 *            the value for gg_ythcj_ryxx.GZDW
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setGzdw(String gzdw) {
		this.gzdw = gzdw == null ? null : gzdw.trim();
	}

	public String getHjdxzqh() {
		return hjdxzqh;
	}

	public void setHjdxzqh(String hjdxzqh) {
		this.hjdxzqh = hjdxzqh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.HJDXZ
	 *
	 * @return the value of gg_ythcj_ryxx.HJDXZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getHjdxz() {
		return hjdxz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.HJDXZ
	 *
	 * @param hjdxz
	 *            the value for gg_ythcj_ryxx.HJDXZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setHjdxz(String hjdxz) {
		this.hjdxz = hjdxz == null ? null : hjdxz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.HJDPCS
	 *
	 * @return the value of gg_ythcj_ryxx.HJDPCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getHjdpcs() {
		return hjdpcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.HJDPCS
	 *
	 * @param hjdpcs
	 *            the value for gg_ythcj_ryxx.HJDPCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setHjdpcs(String hjdpcs) {
		this.hjdpcs = hjdpcs == null ? null : hjdpcs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XZD
	 *
	 * @return the value of gg_ythcj_ryxx.XZD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXzd() {
		return xzd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XZD
	 *
	 * @param xzd
	 *            the value for gg_ythcj_ryxx.XZD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXzd(String xzd) {
		this.xzd = xzd == null ? null : xzd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XZDXZ
	 *
	 * @return the value of gg_ythcj_ryxx.XZDXZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXzdxz() {
		return xzdxz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XZDXZ
	 *
	 * @param xzdxz
	 *            the value for gg_ythcj_ryxx.XZDXZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXzdxz(String xzdxz) {
		this.xzdxz = xzdxz == null ? null : xzdxz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XZDXZ_X
	 *
	 * @return the value of gg_ythcj_ryxx.XZDXZ_X
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXzdxzX() {
		return xzdxzX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XZDXZ_X
	 *
	 * @param xzdxzX
	 *            the value for gg_ythcj_ryxx.XZDXZ_X
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXzdxzX(String xzdxzX) {
		this.xzdxzX = xzdxzX == null ? null : xzdxzX.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XZDXZ_Y
	 *
	 * @return the value of gg_ythcj_ryxx.XZDXZ_Y
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXzdxzY() {
		return xzdxzY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XZDXZ_Y
	 *
	 * @param xzdxzY
	 *            the value for gg_ythcj_ryxx.XZDXZ_Y
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXzdxzY(String xzdxzY) {
		this.xzdxzY = xzdxzY == null ? null : xzdxzY.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XZDPCS
	 *
	 * @return the value of gg_ythcj_ryxx.XZDPCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXzdpcs() {
		return xzdpcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XZDPCS
	 *
	 * @param xzdpcs
	 *            the value for gg_ythcj_ryxx.XZDPCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXzdpcs(String xzdpcs) {
		this.xzdpcs = xzdpcs == null ? null : xzdpcs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XZSQ
	 *
	 * @return the value of gg_ythcj_ryxx.XZSQ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXzsq() {
		return xzsq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XZSQ
	 *
	 * @param xzsq
	 *            the value for gg_ythcj_ryxx.XZSQ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXzsq(String xzsq) {
		this.xzsq = xzsq == null ? null : xzsq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LJQH
	 *
	 * @return the value of gg_ythcj_ryxx.LJQH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getLjqh() {
		return ljqh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LJQH
	 *
	 * @param ljqh
	 *            the value for gg_ythcj_ryxx.LJQH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLjqh(String ljqh) {
		this.ljqh = ljqh == null ? null : ljqh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LJDMC
	 *
	 * @return the value of gg_ythcj_ryxx.LJDMC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getLjdmc() {
		return ljdmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LJDMC
	 *
	 * @param ljdmc
	 *            the value for gg_ythcj_ryxx.LJDMC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLjdmc(String ljdmc) {
		this.ljdmc = ljdmc == null ? null : ljdmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LJTD
	 *
	 * @return the value of gg_ythcj_ryxx.LJTD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getLjtd() {
		return ljtd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LJTD
	 *
	 * @param ljtd
	 *            the value for gg_ythcj_ryxx.LJTD
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLjtd(String ljtd) {
		this.ljtd = ljtd == null ? null : ljtd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LJCS
	 *
	 * @return the value of gg_ythcj_ryxx.LJCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getLjcs() {
		return ljcs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LJCS
	 *
	 * @param ljcs
	 *            the value for gg_ythcj_ryxx.LJCS
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLjcs(String ljcs) {
		this.ljcs = ljcs == null ? null : ljcs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LJBW
	 *
	 * @return the value of gg_ythcj_ryxx.LJBW
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getLjbw() {
		return ljbw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LJBW
	 *
	 * @param ljbw
	 *            the value for gg_ythcj_ryxx.LJBW
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLjbw(String ljbw) {
		this.ljbw = ljbw == null ? null : ljbw.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.JZSJ
	 *
	 * @return the value of gg_ythcj_ryxx.JZSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getJzsj() {
		return jzsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.JZSJ
	 *
	 * @param jzsj
	 *            the value for gg_ythcj_ryxx.JZSJ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setJzsj(String jzsj) {
		this.jzsj = jzsj == null ? null : jzsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.SG
	 *
	 * @return the value of gg_ythcj_ryxx.SG
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getSg() {
		return sg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.SG
	 *
	 * @param sg
	 *            the value for gg_ythcj_ryxx.SG
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setSg(String sg) {
		this.sg = sg == null ? null : sg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TZ
	 *
	 * @return the value of gg_ythcj_ryxx.TZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTz() {
		return tz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TZ
	 *
	 * @param tz
	 *            the value for gg_ythcj_ryxx.TZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTz(String tz) {
		this.tz = tz == null ? null : tz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ZC
	 *
	 * @return the value of gg_ythcj_ryxx.ZC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getZc() {
		return zc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ZC
	 *
	 * @param zc
	 *            the value for gg_ythcj_ryxx.ZC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setZc(String zc) {
		this.zc = zc == null ? null : zc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.XX
	 *
	 * @return the value of gg_ythcj_ryxx.XX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getXx() {
		return xx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.XX
	 *
	 * @param xx
	 *            the value for gg_ythcj_ryxx.XX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setXx(String xx) {
		this.xx = xx == null ? null : xx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LX
	 *
	 * @return the value of gg_ythcj_ryxx.LX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getLx() {
		return lx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LX
	 *
	 * @param lx
	 *            the value for gg_ythcj_ryxx.LX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLx(String lx) {
		this.lx = lx == null ? null : lx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TX
	 *
	 * @return the value of gg_ythcj_ryxx.TX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTx() {
		return tx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TX
	 *
	 * @param tx
	 *            the value for gg_ythcj_ryxx.TX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTx(String tx) {
		this.tx = tx == null ? null : tx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ZHC
	 *
	 * @return the value of gg_ythcj_ryxx.ZHC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getZhc() {
		return zhc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ZHC
	 *
	 * @param zhc
	 *            the value for gg_ythcj_ryxx.ZHC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setZhc(String zhc) {
		this.zhc = zhc == null ? null : zhc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TBBJ11
	 *
	 * @return the value of gg_ythcj_ryxx.TBBJ11
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTbbj11() {
		return tbbj11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TBBJ11
	 *
	 * @param tbbj11
	 *            the value for gg_ythcj_ryxx.TBBJ11
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTbbj11(String tbbj11) {
		this.tbbj11 = tbbj11 == null ? null : tbbj11.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TBBJ12
	 *
	 * @return the value of gg_ythcj_ryxx.TBBJ12
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTbbj12() {
		return tbbj12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TBBJ12
	 *
	 * @param tbbj12
	 *            the value for gg_ythcj_ryxx.TBBJ12
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTbbj12(String tbbj12) {
		this.tbbj12 = tbbj12 == null ? null : tbbj12.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TBBJ13
	 *
	 * @return the value of gg_ythcj_ryxx.TBBJ13
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTbbj13() {
		return tbbj13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TBBJ13
	 *
	 * @param tbbj13
	 *            the value for gg_ythcj_ryxx.TBBJ13
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTbbj13(String tbbj13) {
		this.tbbj13 = tbbj13 == null ? null : tbbj13.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TBBJ14
	 *
	 * @return the value of gg_ythcj_ryxx.TBBJ14
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTbbj14() {
		return tbbj14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TBBJ14
	 *
	 * @param tbbj14
	 *            the value for gg_ythcj_ryxx.TBBJ14
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTbbj14(String tbbj14) {
		this.tbbj14 = tbbj14 == null ? null : tbbj14.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TSTZ
	 *
	 * @return the value of gg_ythcj_ryxx.TSTZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTstz() {
		return tstz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TSTZ
	 *
	 * @param tstz
	 *            the value for gg_ythcj_ryxx.TSTZ
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTstz(String tstz) {
		this.tstz = tstz == null ? null : tstz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TBBJ21
	 *
	 * @return the value of gg_ythcj_ryxx.TBBJ21
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTbbj21() {
		return tbbj21;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TBBJ21
	 *
	 * @param tbbj21
	 *            the value for gg_ythcj_ryxx.TBBJ21
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTbbj21(String tbbj21) {
		this.tbbj21 = tbbj21 == null ? null : tbbj21.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TBBJ22
	 *
	 * @return the value of gg_ythcj_ryxx.TBBJ22
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTbbj22() {
		return tbbj22;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TBBJ22
	 *
	 * @param tbbj22
	 *            the value for gg_ythcj_ryxx.TBBJ22
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTbbj22(String tbbj22) {
		this.tbbj22 = tbbj22 == null ? null : tbbj22.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TBBJ23
	 *
	 * @return the value of gg_ythcj_ryxx.TBBJ23
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTbbj23() {
		return tbbj23;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TBBJ23
	 *
	 * @param tbbj23
	 *            the value for gg_ythcj_ryxx.TBBJ23
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTbbj23(String tbbj23) {
		this.tbbj23 = tbbj23 == null ? null : tbbj23.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.TBBJ24
	 *
	 * @return the value of gg_ythcj_ryxx.TBBJ24
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getTbbj24() {
		return tbbj24;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.TBBJ24
	 *
	 * @param tbbj24
	 *            the value for gg_ythcj_ryxx.TBBJ24
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setTbbj24(String tbbj24) {
		this.tbbj24 = tbbj24 == null ? null : tbbj24.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ZWBH
	 *
	 * @return the value of gg_ythcj_ryxx.ZWBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getZwbh() {
		return zwbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ZWBH
	 *
	 * @param zwbh
	 *            the value for gg_ythcj_ryxx.ZWBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setZwbh(String zwbh) {
		this.zwbh = zwbh == null ? null : zwbh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.DNABH
	 *
	 * @return the value of gg_ythcj_ryxx.DNABH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getDnabh() {
		return dnabh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.DNABH
	 *
	 * @param dnabh
	 *            the value for gg_ythcj_ryxx.DNABH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setDnabh(String dnabh) {
		this.dnabh = dnabh == null ? null : dnabh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ZJBH
	 *
	 * @return the value of gg_ythcj_ryxx.ZJBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getZjbh() {
		return zjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ZJBH
	 *
	 * @param zjbh
	 *            the value for gg_ythcj_ryxx.ZJBH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setZjbh(String zjbh) {
		this.zjbh = zjbh == null ? null : zjbh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.LXDH2
	 *
	 * @return the value of gg_ythcj_ryxx.LXDH2
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getLxdh2() {
		return lxdh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.LXDH2
	 *
	 * @param lxdh2
	 *            the value for gg_ythcj_ryxx.LXDH2
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setLxdh2(String lxdh2) {
		this.lxdh2 = lxdh2 == null ? null : lxdh2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.RYZP
	 *
	 * @return the value of gg_ythcj_ryxx.RYZP
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getRyzp() {
		return ryzp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.RYZP
	 *
	 * @param ryzp
	 *            the value for gg_ythcj_ryxx.RYZP
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setRyzp(String ryzp) {
		this.ryzp = ryzp == null ? null : ryzp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.SDQK
	 *
	 * @return the value of gg_ythcj_ryxx.SDQK
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getSdqk() {
		return sdqk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.SDQK
	 *
	 * @param sdqk
	 *            the value for gg_ythcj_ryxx.SDQK
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setSdqk(String sdqk) {
		this.sdqk = sdqk == null ? null : sdqk.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.DJQK
	 *
	 * @return the value of gg_ythcj_ryxx.DJQK
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getDjqk() {
		return djqk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.DJQK
	 *
	 * @param djqk
	 *            the value for gg_ythcj_ryxx.DJQK
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setDjqk(String djqk) {
		this.djqk = djqk == null ? null : djqk.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ZBDW_BH
	 *
	 * @return the value of gg_ythcj_ryxx.ZBDW_BH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getZbdwBh() {
		return zbdwBh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ZBDW_BH
	 *
	 * @param zbdwBh
	 *            the value for gg_ythcj_ryxx.ZBDW_BH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setZbdwBh(String zbdwBh) {
		this.zbdwBh = zbdwBh == null ? null : zbdwBh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ZBDW_MC
	 *
	 * @return the value of gg_ythcj_ryxx.ZBDW_MC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getZbdwMc() {
		return zbdwMc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ZBDW_MC
	 *
	 * @param zbdwMc
	 *            the value for gg_ythcj_ryxx.ZBDW_MC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setZbdwMc(String zbdwMc) {
		this.zbdwMc = zbdwMc == null ? null : zbdwMc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.RYLX
	 *
	 * @return the value of gg_ythcj_ryxx.RYLX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getRylx() {
		return rylx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.RYLX
	 *
	 * @param rylx
	 *            the value for gg_ythcj_ryxx.RYLX
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setRylx(String rylx) {
		this.rylx = rylx == null ? null : rylx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ZMZP_PATH
	 *
	 * @return the value of gg_ythcj_ryxx.ZMZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getZmzpPath() {
		return zmzpPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ZMZP_PATH
	 *
	 * @param zmzpPath
	 *            the value for gg_ythcj_ryxx.ZMZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setZmzpPath(String zmzpPath) {
		this.zmzpPath = zmzpPath == null ? null : zmzpPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.ZCZP_PATH
	 *
	 * @return the value of gg_ythcj_ryxx.ZCZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getZczpPath() {
		return zczpPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.ZCZP_PATH
	 *
	 * @param zczpPath
	 *            the value for gg_ythcj_ryxx.ZCZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setZczpPath(String zczpPath) {
		this.zczpPath = zczpPath == null ? null : zczpPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.YCZP_PATH
	 *
	 * @return the value of gg_ythcj_ryxx.YCZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public String getYczpPath() {
		return yczpPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.YCZP_PATH
	 *
	 * @param yczpPath
	 *            the value for gg_ythcj_ryxx.YCZP_PATH
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setYczpPath(String yczpPath) {
		this.yczpPath = yczpPath == null ? null : yczpPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.RYZP_ZM
	 *
	 * @return the value of gg_ythcj_ryxx.RYZP_ZM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public byte[] getRyzpZm() {
		return ryzpZm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.RYZP_ZM
	 *
	 * @param ryzpZm
	 *            the value for gg_ythcj_ryxx.RYZP_ZM
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setRyzpZm(byte[] ryzpZm) {
		this.ryzpZm = ryzpZm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.RYZP_ZC
	 *
	 * @return the value of gg_ythcj_ryxx.RYZP_ZC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public byte[] getRyzpZc() {
		return ryzpZc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.RYZP_ZC
	 *
	 * @param ryzpZc
	 *            the value for gg_ythcj_ryxx.RYZP_ZC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setRyzpZc(byte[] ryzpZc) {
		this.ryzpZc = ryzpZc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gg_ythcj_ryxx.RYZP_YC
	 *
	 * @return the value of gg_ythcj_ryxx.RYZP_YC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public byte[] getRyzpYc() {
		return ryzpYc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gg_ythcj_ryxx.RYZP_YC
	 *
	 * @param ryzpYc
	 *            the value for gg_ythcj_ryxx.RYZP_YC
	 *
	 * @mbg.generated Thu Nov 16 16:51:23 CST 2017
	 */
	public void setRyzpYc(byte[] ryzpYc) {
		this.ryzpYc = ryzpYc;
	}

	public String getRyzpZmBase64() {
		return ryzpZmBase64;
	}

	public void setRyzpZmBase64(String ryzpZmBase64) {
		this.ryzpZmBase64 = ryzpZmBase64;
	}

	public String getRyzpZcBase64() {
		return ryzpZcBase64;
	}

	public void setRyzpZcBase64(String ryzpZcBase64) {
		this.ryzpZcBase64 = ryzpZcBase64;
	}

	public String getRyzpYcBase64() {
		return ryzpYcBase64;
	}

	public void setRyzpYcBase64(String ryzpYcBase64) {
		this.ryzpYcBase64 = ryzpYcBase64;
	}

	public String getMfqk() {
		return mfqk;
	}

	public void setMfqk(String mfqk) {
		this.mfqk = mfqk;
	}
}