package com.wckj.chasstage.modules.ythcj.entity;

import java.util.Date;

public class ChasYthcjWlxx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.ID
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.ISDEL
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.dataflag
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String dataflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.LRR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.LRSJ
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.XGR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.XGSJ
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.RYXX_ID
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String ryxxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.RYXM
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String ryxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.RYBH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String rybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.WLPTMC
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String wlptmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.WM
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String wm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.WLSFH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String wlsfh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.DZYX
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private String dzyx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_wlxx.PX
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    private Integer px;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.ID
     *
     * @return the value of gg_ythcj_ry_wlxx.ID
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.ID
     *
     * @param id the value for gg_ythcj_ry_wlxx.ID
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.ISDEL
     *
     * @return the value of gg_ythcj_ry_wlxx.ISDEL
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.ISDEL
     *
     * @param isdel the value for gg_ythcj_ry_wlxx.ISDEL
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.dataflag
     *
     * @return the value of gg_ythcj_ry_wlxx.dataflag
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getDataflag() {
        return dataflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.dataflag
     *
     * @param dataflag the value for gg_ythcj_ry_wlxx.dataflag
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setDataflag(String dataflag) {
        this.dataflag = dataflag == null ? null : dataflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.LRR_SFZH
     *
     * @return the value of gg_ythcj_ry_wlxx.LRR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.LRR_SFZH
     *
     * @param lrrSfzh the value for gg_ythcj_ry_wlxx.LRR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.LRSJ
     *
     * @return the value of gg_ythcj_ry_wlxx.LRSJ
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.LRSJ
     *
     * @param lrsj the value for gg_ythcj_ry_wlxx.LRSJ
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.XGR_SFZH
     *
     * @return the value of gg_ythcj_ry_wlxx.XGR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.XGR_SFZH
     *
     * @param xgrSfzh the value for gg_ythcj_ry_wlxx.XGR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.XGSJ
     *
     * @return the value of gg_ythcj_ry_wlxx.XGSJ
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.XGSJ
     *
     * @param xgsj the value for gg_ythcj_ry_wlxx.XGSJ
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.RYXX_ID
     *
     * @return the value of gg_ythcj_ry_wlxx.RYXX_ID
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getRyxxId() {
        return ryxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.RYXX_ID
     *
     * @param ryxxId the value for gg_ythcj_ry_wlxx.RYXX_ID
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setRyxxId(String ryxxId) {
        this.ryxxId = ryxxId == null ? null : ryxxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.RYXM
     *
     * @return the value of gg_ythcj_ry_wlxx.RYXM
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getRyxm() {
        return ryxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.RYXM
     *
     * @param ryxm the value for gg_ythcj_ry_wlxx.RYXM
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setRyxm(String ryxm) {
        this.ryxm = ryxm == null ? null : ryxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.RYBH
     *
     * @return the value of gg_ythcj_ry_wlxx.RYBH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getRybh() {
        return rybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.RYBH
     *
     * @param rybh the value for gg_ythcj_ry_wlxx.RYBH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setRybh(String rybh) {
        this.rybh = rybh == null ? null : rybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.WLPTMC
     *
     * @return the value of gg_ythcj_ry_wlxx.WLPTMC
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getWlptmc() {
        return wlptmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.WLPTMC
     *
     * @param wlptmc the value for gg_ythcj_ry_wlxx.WLPTMC
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setWlptmc(String wlptmc) {
        this.wlptmc = wlptmc == null ? null : wlptmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.WM
     *
     * @return the value of gg_ythcj_ry_wlxx.WM
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getWm() {
        return wm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.WM
     *
     * @param wm the value for gg_ythcj_ry_wlxx.WM
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setWm(String wm) {
        this.wm = wm == null ? null : wm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.WLSFH
     *
     * @return the value of gg_ythcj_ry_wlxx.WLSFH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getWlsfh() {
        return wlsfh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.WLSFH
     *
     * @param wlsfh the value for gg_ythcj_ry_wlxx.WLSFH
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setWlsfh(String wlsfh) {
        this.wlsfh = wlsfh == null ? null : wlsfh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.DZYX
     *
     * @return the value of gg_ythcj_ry_wlxx.DZYX
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public String getDzyx() {
        return dzyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.DZYX
     *
     * @param dzyx the value for gg_ythcj_ry_wlxx.DZYX
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setDzyx(String dzyx) {
        this.dzyx = dzyx == null ? null : dzyx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_wlxx.PX
     *
     * @return the value of gg_ythcj_ry_wlxx.PX
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public Integer getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_wlxx.PX
     *
     * @param px the value for gg_ythcj_ry_wlxx.PX
     *
     * @mbg.generated Thu Nov 16 19:11:39 CST 2017
     */
    public void setPx(Integer px) {
        this.px = px;
    }
}