package com.wckj.chasstage.modules.ythcj.entity;

import java.util.Date;

public class ChasYthcjShgx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.ID
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.ISDEL
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.dataflag
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String dataflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.LRR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.LRSJ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.XGR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.XGSJ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.RYXX_ID
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String ryxxId;
    
    private String gx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.XM
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.XB
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String xb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.HJD
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String hjd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.HJDXZ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String hjdxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String sfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.LXDH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private String lxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gg_ythcj_ry_shgx.PX
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    private Integer px;
    
    
    private String rybh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.ID
     *
     * @return the value of gg_ythcj_ry_shgx.ID
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.ID
     *
     * @param id the value for gg_ythcj_ry_shgx.ID
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.ISDEL
     *
     * @return the value of gg_ythcj_ry_shgx.ISDEL
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.ISDEL
     *
     * @param isdel the value for gg_ythcj_ry_shgx.ISDEL
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.dataflag
     *
     * @return the value of gg_ythcj_ry_shgx.dataflag
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getDataflag() {
        return dataflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.dataflag
     *
     * @param dataflag the value for gg_ythcj_ry_shgx.dataflag
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setDataflag(String dataflag) {
        this.dataflag = dataflag == null ? null : dataflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.LRR_SFZH
     *
     * @return the value of gg_ythcj_ry_shgx.LRR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.LRR_SFZH
     *
     * @param lrrSfzh the value for gg_ythcj_ry_shgx.LRR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.LRSJ
     *
     * @return the value of gg_ythcj_ry_shgx.LRSJ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.LRSJ
     *
     * @param lrsj the value for gg_ythcj_ry_shgx.LRSJ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.XGR_SFZH
     *
     * @return the value of gg_ythcj_ry_shgx.XGR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.XGR_SFZH
     *
     * @param xgrSfzh the value for gg_ythcj_ry_shgx.XGR_SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.XGSJ
     *
     * @return the value of gg_ythcj_ry_shgx.XGSJ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.XGSJ
     *
     * @param xgsj the value for gg_ythcj_ry_shgx.XGSJ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.RYXX_ID
     *
     * @return the value of gg_ythcj_ry_shgx.RYXX_ID
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getRyxxId() {
        return ryxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.RYXX_ID
     *
     * @param ryxxId the value for gg_ythcj_ry_shgx.RYXX_ID
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setRyxxId(String ryxxId) {
        this.ryxxId = ryxxId == null ? null : ryxxId.trim();
    }

    public String getGx() {
        return gx;
    }

    public void setGx(String gx) {
        this.gx = gx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.XM
     *
     * @return the value of gg_ythcj_ry_shgx.XM
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.XM
     *
     * @param xm the value for gg_ythcj_ry_shgx.XM
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.XB
     *
     * @return the value of gg_ythcj_ry_shgx.XB
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.XB
     *
     * @param xb the value for gg_ythcj_ry_shgx.XB
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.HJD
     *
     * @return the value of gg_ythcj_ry_shgx.HJD
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getHjd() {
        return hjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.HJD
     *
     * @param hjd the value for gg_ythcj_ry_shgx.HJD
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setHjd(String hjd) {
        this.hjd = hjd == null ? null : hjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.HJDXZ
     *
     * @return the value of gg_ythcj_ry_shgx.HJDXZ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getHjdxz() {
        return hjdxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.HJDXZ
     *
     * @param hjdxz the value for gg_ythcj_ry_shgx.HJDXZ
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setHjdxz(String hjdxz) {
        this.hjdxz = hjdxz == null ? null : hjdxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.SFZH
     *
     * @return the value of gg_ythcj_ry_shgx.SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.SFZH
     *
     * @param sfzh the value for gg_ythcj_ry_shgx.SFZH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.LXDH
     *
     * @return the value of gg_ythcj_ry_shgx.LXDH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.LXDH
     *
     * @param lxdh the value for gg_ythcj_ry_shgx.LXDH
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gg_ythcj_ry_shgx.PX
     *
     * @return the value of gg_ythcj_ry_shgx.PX
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public Integer getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gg_ythcj_ry_shgx.PX
     *
     * @param px the value for gg_ythcj_ry_shgx.PX
     *
     * @mbg.generated Thu Nov 16 19:24:54 CST 2017
     */
    public void setPx(Integer px) {
        this.px = px;
    }
    
    public String getRybh() {
        return rybh;
    }
    public void setRybh(String rybh) {
        this.rybh = rybh == null ? null : rybh.trim();
    }
}