package com.wckj.chasstage.modules.njjl.entity;

import java.util.Date;

public class ChasYwNjRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.id
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.isdel
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.data_flag
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String dataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.lrr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.lrsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.xgr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.xgsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.nybh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String nybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.bjcr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String bjcrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.bjcr_xm
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String bjcrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.czmj_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String czmjSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.czmj_xm
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String czmjXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.cqsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private Date cqsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.sjbq
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private Date sjbq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.zbdw_bh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String zbdwBh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.zbdw_mc
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String zbdwMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.dwxtbh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String dwxtbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_nj_record.czlx
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    private String czlx;

    private String rybh;

    private String businessId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.id
     *
     * @return the value of chas_yw_nj_record.id
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.id
     *
     * @param id the value for chas_yw_nj_record.id
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public Integer getIsdel() {
        return isdel;
    }

    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.data_flag
     *
     * @return the value of chas_yw_nj_record.data_flag
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.data_flag
     *
     * @param dataFlag the value for chas_yw_nj_record.data_flag
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.lrr_sfzh
     *
     * @return the value of chas_yw_nj_record.lrr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.lrr_sfzh
     *
     * @param lrrSfzh the value for chas_yw_nj_record.lrr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.lrsj
     *
     * @return the value of chas_yw_nj_record.lrsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.lrsj
     *
     * @param lrsj the value for chas_yw_nj_record.lrsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.xgr_sfzh
     *
     * @return the value of chas_yw_nj_record.xgr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.xgr_sfzh
     *
     * @param xgrSfzh the value for chas_yw_nj_record.xgr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.xgsj
     *
     * @return the value of chas_yw_nj_record.xgsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.xgsj
     *
     * @param xgsj the value for chas_yw_nj_record.xgsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.nybh
     *
     * @return the value of chas_yw_nj_record.nybh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getNybh() {
        return nybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.nybh
     *
     * @param nybh the value for chas_yw_nj_record.nybh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setNybh(String nybh) {
        this.nybh = nybh == null ? null : nybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.bjcr_sfzh
     *
     * @return the value of chas_yw_nj_record.bjcr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getBjcrSfzh() {
        return bjcrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.bjcr_sfzh
     *
     * @param bjcrSfzh the value for chas_yw_nj_record.bjcr_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setBjcrSfzh(String bjcrSfzh) {
        this.bjcrSfzh = bjcrSfzh == null ? null : bjcrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.bjcr_xm
     *
     * @return the value of chas_yw_nj_record.bjcr_xm
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getBjcrXm() {
        return bjcrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.bjcr_xm
     *
     * @param bjcrXm the value for chas_yw_nj_record.bjcr_xm
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setBjcrXm(String bjcrXm) {
        this.bjcrXm = bjcrXm == null ? null : bjcrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.czmj_sfzh
     *
     * @return the value of chas_yw_nj_record.czmj_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getCzmjSfzh() {
        return czmjSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.czmj_sfzh
     *
     * @param czmjSfzh the value for chas_yw_nj_record.czmj_sfzh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setCzmjSfzh(String czmjSfzh) {
        this.czmjSfzh = czmjSfzh == null ? null : czmjSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.czmj_xm
     *
     * @return the value of chas_yw_nj_record.czmj_xm
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getCzmjXm() {
        return czmjXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.czmj_xm
     *
     * @param czmjXm the value for chas_yw_nj_record.czmj_xm
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setCzmjXm(String czmjXm) {
        this.czmjXm = czmjXm == null ? null : czmjXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.cqsj
     *
     * @return the value of chas_yw_nj_record.cqsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public Date getCqsj() {
        return cqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.cqsj
     *
     * @param cqsj the value for chas_yw_nj_record.cqsj
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setCqsj(Date cqsj) {
        this.cqsj = cqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.sjbq
     *
     * @return the value of chas_yw_nj_record.sjbq
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public Date getSjbq() {
        return sjbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.sjbq
     *
     * @param sjbq the value for chas_yw_nj_record.sjbq
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setSjbq(Date sjbq) {
        this.sjbq = sjbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.zbdw_bh
     *
     * @return the value of chas_yw_nj_record.zbdw_bh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getZbdwBh() {
        return zbdwBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.zbdw_bh
     *
     * @param zbdwBh the value for chas_yw_nj_record.zbdw_bh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setZbdwBh(String zbdwBh) {
        this.zbdwBh = zbdwBh == null ? null : zbdwBh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.zbdw_mc
     *
     * @return the value of chas_yw_nj_record.zbdw_mc
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getZbdwMc() {
        return zbdwMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.zbdw_mc
     *
     * @param zbdwMc the value for chas_yw_nj_record.zbdw_mc
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setZbdwMc(String zbdwMc) {
        this.zbdwMc = zbdwMc == null ? null : zbdwMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.dwxtbh
     *
     * @return the value of chas_yw_nj_record.dwxtbh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getDwxtbh() {
        return dwxtbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.dwxtbh
     *
     * @param dwxtbh the value for chas_yw_nj_record.dwxtbh
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setDwxtbh(String dwxtbh) {
        this.dwxtbh = dwxtbh == null ? null : dwxtbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_nj_record.czlx
     *
     * @return the value of chas_yw_nj_record.czlx
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public String getCzlx() {
        return czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_nj_record.czlx
     *
     * @param czlx the value for chas_yw_nj_record.czlx
     *
     * @mbg.generated Mon Aug 24 09:44:53 CST 2020
     */
    public void setCzlx(String czlx) {
        this.czlx = czlx == null ? null : czlx.trim();
    }

    public String getRybh() {
        return rybh;
    }

    public void setRybh(String rybh) {
        this.rybh = rybh;
    }

    public String getBusinessId() {
        return businessId;
    }

    public void setBusinessId(String businessId) {
        this.businessId = businessId;
    }
}