package com.wckj.chasstage.modules.gnpz.entity;

import com.alibaba.fastjson.JSONObject;

import java.util.Date;
import java.util.Map;

public class ChasXtGnpz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.id
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private String id;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.name
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.pxh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private Integer pxh;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.sbpz
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private String sbpz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.isdel
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.lrsj
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.lrr_sfzh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.xgsj
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_gnpz.xgr_sfzh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    private String xgrSfzh;

    private String gnpz;

    private String sfkbj;

    private String zdypz;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.id
     *
     * @return the value of chas_xt_gnpz.id
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.id
     *
     * @param id the value for chas_xt_gnpz.id
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.name
     *
     * @return the value of chas_xt_gnpz.name
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.name
     *
     * @param name the value for chas_xt_gnpz.name
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.pxh
     *
     * @return the value of chas_xt_gnpz.pxh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public Integer getPxh() {
        return pxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.pxh
     *
     * @param pxh the value for chas_xt_gnpz.pxh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setPxh(Integer pxh) {
        this.pxh = pxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.sbpz
     *
     * @return the value of chas_xt_gnpz.sbpz
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public String getSbpz() {
        return sbpz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.sbpz
     *
     * @param sbpz the value for chas_xt_gnpz.sbpz
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setSbpz(String sbpz) {
        this.sbpz = sbpz == null ? null : sbpz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.isdel
     *
     * @return the value of chas_xt_gnpz.isdel
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.isdel
     *
     * @param isdel the value for chas_xt_gnpz.isdel
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.lrsj
     *
     * @return the value of chas_xt_gnpz.lrsj
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.lrsj
     *
     * @param lrsj the value for chas_xt_gnpz.lrsj
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.lrr_sfzh
     *
     * @return the value of chas_xt_gnpz.lrr_sfzh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.lrr_sfzh
     *
     * @param lrrSfzh the value for chas_xt_gnpz.lrr_sfzh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.xgsj
     *
     * @return the value of chas_xt_gnpz.xgsj
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.xgsj
     *
     * @param xgsj the value for chas_xt_gnpz.xgsj
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_gnpz.xgr_sfzh
     *
     * @return the value of chas_xt_gnpz.xgr_sfzh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_gnpz.xgr_sfzh
     *
     * @param xgrSfzh the value for chas_xt_gnpz.xgr_sfzh
     *
     * @mbg.generated Sun Oct 11 13:47:44 CST 2020
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    public String getGnpz() {
        return gnpz;
    }

    public void setGnpz(String gnpz) {
        this.gnpz = gnpz;
    }

    public String getSfkbj() {
        return sfkbj;
    }

    public void setSfkbj(String sfkbj) {
        this.sfkbj = sfkbj;
    }

    public String getZdypz() {
        return zdypz;
    }

    public void setZdypz(String zdypz) {
        this.zdypz = zdypz;
    }

    public String getZdypzVule(String key){
        try {
            Map<String,Object> map = JSONObject.parseObject(this.zdypz, Map.class);
            String value = (String) map.get(key);
            return value;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}
