package com.wckj.chasstage.modules.njxx.entity;

import java.util.Date;

public class ChasYwNj {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.ID
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.ISDEL
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private Integer isdel;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.dataflag
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String dataflag;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.LRR_SFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String lrrSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.LRSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private Date lrsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.XGR_SFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String xgrSfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.XGSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private Date xgsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.baqid
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String baqid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.BAQMC
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String baqmc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.ZBDW_BH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String zbdwBh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.ZBDW_MC
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String zbdwMc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.ZBRSFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String zbrsfzh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.ZBRXM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String zbrxm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.TFSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private Date tfsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.WSH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String wsh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.RYBH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String rybh;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.RYXM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String ryxm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.XB
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String xb;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.CSRQ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private Date csrq;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.ZJLB
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String zjlb;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.ZJHM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String zjhm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.XCJCSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private Date xcjcsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.XCJCDD
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String xcjcdd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.XCJCFF
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String xcjcff;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.XCJCJG
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String xcjcjg;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.JCSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private Date jcsj;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column chas_yw_nj.GZ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	private String gz;
	private String dwxtbh;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.ID
	 *
	 * @return the value of chas_yw_nj.ID
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.ID
	 *
	 * @param id
	 *            the value for chas_yw_nj.ID
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	public String getDwxtbh() {
		return dwxtbh;
	}

	public void setDwxtbh(String dwxtbh) {
		this.dwxtbh = dwxtbh == null ? null : dwxtbh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.ISDEL
	 *
	 * @return the value of chas_yw_nj.ISDEL
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public Integer getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.ISDEL
	 *
	 * @param isdel
	 *            the value for chas_yw_nj.ISDEL
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.dataflag
	 *
	 * @return the value of chas_yw_nj.dataflag
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getDataflag() {
		return dataflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.dataflag
	 *
	 * @param dataflag
	 *            the value for chas_yw_nj.dataflag
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setDataflag(String dataflag) {
		this.dataflag = dataflag == null ? null : dataflag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.LRR_SFZH
	 *
	 * @return the value of chas_yw_nj.LRR_SFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getLrrSfzh() {
		return lrrSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.LRR_SFZH
	 *
	 * @param lrrSfzh
	 *            the value for chas_yw_nj.LRR_SFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setLrrSfzh(String lrrSfzh) {
		this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.LRSJ
	 *
	 * @return the value of chas_yw_nj.LRSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public Date getLrsj() {
		return lrsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.LRSJ
	 *
	 * @param lrsj
	 *            the value for chas_yw_nj.LRSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setLrsj(Date lrsj) {
		this.lrsj = lrsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.XGR_SFZH
	 *
	 * @return the value of chas_yw_nj.XGR_SFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getXgrSfzh() {
		return xgrSfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.XGR_SFZH
	 *
	 * @param xgrSfzh
	 *            the value for chas_yw_nj.XGR_SFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setXgrSfzh(String xgrSfzh) {
		this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.XGSJ
	 *
	 * @return the value of chas_yw_nj.XGSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public Date getXgsj() {
		return xgsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.XGSJ
	 *
	 * @param xgsj
	 *            the value for chas_yw_nj.XGSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setXgsj(Date xgsj) {
		this.xgsj = xgsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.baqid
	 *
	 * @return the value of chas_yw_nj.baqid
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getBaqid() {
		return baqid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.baqid
	 *
	 * @param baqid
	 *            the value for chas_yw_nj.baqid
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setBaqid(String baqid) {
		this.baqid = baqid == null ? null : baqid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.BAQMC
	 *
	 * @return the value of chas_yw_nj.BAQMC
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getBaqmc() {
		return baqmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.BAQMC
	 *
	 * @param baqmc
	 *            the value for chas_yw_nj.BAQMC
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setBaqmc(String baqmc) {
		this.baqmc = baqmc == null ? null : baqmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.ZBDW_BH
	 *
	 * @return the value of chas_yw_nj.ZBDW_BH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getZbdwBh() {
		return zbdwBh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.ZBDW_BH
	 *
	 * @param zbdwBh
	 *            the value for chas_yw_nj.ZBDW_BH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setZbdwBh(String zbdwBh) {
		this.zbdwBh = zbdwBh == null ? null : zbdwBh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.ZBDW_MC
	 *
	 * @return the value of chas_yw_nj.ZBDW_MC
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getZbdwMc() {
		return zbdwMc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.ZBDW_MC
	 *
	 * @param zbdwMc
	 *            the value for chas_yw_nj.ZBDW_MC
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setZbdwMc(String zbdwMc) {
		this.zbdwMc = zbdwMc == null ? null : zbdwMc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.ZBRSFZH
	 *
	 * @return the value of chas_yw_nj.ZBRSFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getZbrsfzh() {
		return zbrsfzh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.ZBRSFZH
	 *
	 * @param zbrsfzh
	 *            the value for chas_yw_nj.ZBRSFZH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setZbrsfzh(String zbrsfzh) {
		this.zbrsfzh = zbrsfzh == null ? null : zbrsfzh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.ZBRXM
	 *
	 * @return the value of chas_yw_nj.ZBRXM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getZbrxm() {
		return zbrxm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.ZBRXM
	 *
	 * @param zbrxm
	 *            the value for chas_yw_nj.ZBRXM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setZbrxm(String zbrxm) {
		this.zbrxm = zbrxm == null ? null : zbrxm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.TFSJ
	 *
	 * @return the value of chas_yw_nj.TFSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public Date getTfsj() {
		return tfsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.TFSJ
	 *
	 * @param tfsj
	 *            the value for chas_yw_nj.TFSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setTfsj(Date tfsj) {
		this.tfsj = tfsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.WSH
	 *
	 * @return the value of chas_yw_nj.WSH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getWsh() {
		return wsh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.WSH
	 *
	 * @param wsh
	 *            the value for chas_yw_nj.WSH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setWsh(String wsh) {
		this.wsh = wsh == null ? null : wsh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.RYBH
	 *
	 * @return the value of chas_yw_nj.RYBH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getRybh() {
		return rybh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.RYBH
	 *
	 * @param rybh
	 *            the value for chas_yw_nj.RYBH
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setRybh(String rybh) {
		this.rybh = rybh == null ? null : rybh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.RYXM
	 *
	 * @return the value of chas_yw_nj.RYXM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getRyxm() {
		return ryxm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.RYXM
	 *
	 * @param ryxm
	 *            the value for chas_yw_nj.RYXM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setRyxm(String ryxm) {
		this.ryxm = ryxm == null ? null : ryxm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.XB
	 *
	 * @return the value of chas_yw_nj.XB
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getXb() {
		return xb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.XB
	 *
	 * @param xb
	 *            the value for chas_yw_nj.XB
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setXb(String xb) {
		this.xb = xb == null ? null : xb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.CSRQ
	 *
	 * @return the value of chas_yw_nj.CSRQ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public Date getCsrq() {
		return csrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.CSRQ
	 *
	 * @param csrq
	 *            the value for chas_yw_nj.CSRQ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setCsrq(Date csrq) {
		this.csrq = csrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.ZJLB
	 *
	 * @return the value of chas_yw_nj.ZJLB
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getZjlb() {
		return zjlb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.ZJLB
	 *
	 * @param zjlb
	 *            the value for chas_yw_nj.ZJLB
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setZjlb(String zjlb) {
		this.zjlb = zjlb == null ? null : zjlb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.ZJHM
	 *
	 * @return the value of chas_yw_nj.ZJHM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getZjhm() {
		return zjhm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.ZJHM
	 *
	 * @param zjhm
	 *            the value for chas_yw_nj.ZJHM
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setZjhm(String zjhm) {
		this.zjhm = zjhm == null ? null : zjhm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.XCJCSJ
	 *
	 * @return the value of chas_yw_nj.XCJCSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public Date getXcjcsj() {
		return xcjcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.XCJCSJ
	 *
	 * @param xcjcsj
	 *            the value for chas_yw_nj.XCJCSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setXcjcsj(Date xcjcsj) {
		this.xcjcsj = xcjcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.XCJCDD
	 *
	 * @return the value of chas_yw_nj.XCJCDD
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getXcjcdd() {
		return xcjcdd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.XCJCDD
	 *
	 * @param xcjcdd
	 *            the value for chas_yw_nj.XCJCDD
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setXcjcdd(String xcjcdd) {
		this.xcjcdd = xcjcdd == null ? null : xcjcdd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.XCJCFF
	 *
	 * @return the value of chas_yw_nj.XCJCFF
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getXcjcff() {
		return xcjcff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.XCJCFF
	 *
	 * @param xcjcff
	 *            the value for chas_yw_nj.XCJCFF
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setXcjcff(String xcjcff) {
		this.xcjcff = xcjcff == null ? null : xcjcff.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.XCJCJG
	 *
	 * @return the value of chas_yw_nj.XCJCJG
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getXcjcjg() {
		return xcjcjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.XCJCJG
	 *
	 * @param xcjcjg
	 *            the value for chas_yw_nj.XCJCJG
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setXcjcjg(String xcjcjg) {
		this.xcjcjg = xcjcjg == null ? null : xcjcjg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.JCSJ
	 *
	 * @return the value of chas_yw_nj.JCSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public Date getJcsj() {
		return jcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.JCSJ
	 *
	 * @param jcsj
	 *            the value for chas_yw_nj.JCSJ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setJcsj(Date jcsj) {
		this.jcsj = jcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column chas_yw_nj.GZ
	 *
	 * @return the value of chas_yw_nj.GZ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public String getGz() {
		return gz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column chas_yw_nj.GZ
	 *
	 * @param gz
	 *            the value for chas_yw_nj.GZ
	 *
	 * @mbg.generated Mon Nov 20 16:34:19 CST 2017
	 */
	public void setGz(String gz) {
		this.gz = gz == null ? null : gz.trim();
	}
}