package com.wckj.chasstage.modules.khdbb.entity;

import java.util.Date;

public class ChasXtBbkz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.LRR_SFZH
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.LRSJ
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.LRR_XM
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String lrrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.XGR_SFZH
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.XGSJ
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.XGR_XM
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String xgrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.ISDEL
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.CLIENT_NO
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String clientNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.CLIENT_TYPE
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.INSTALL_ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String installId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.UPDATE_ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.RECENT
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private Integer recent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.EXPLAIN
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String explain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_bbkz.DATA_FLAG
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    private String dataFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.ID
     *
     * @return the value of chas_xt_bbkz.ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.ID
     *
     * @param id the value for chas_xt_bbkz.ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.LRR_SFZH
     *
     * @return the value of chas_xt_bbkz.LRR_SFZH
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.LRR_SFZH
     *
     * @param lrrSfzh the value for chas_xt_bbkz.LRR_SFZH
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.LRSJ
     *
     * @return the value of chas_xt_bbkz.LRSJ
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.LRSJ
     *
     * @param lrsj the value for chas_xt_bbkz.LRSJ
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.LRR_XM
     *
     * @return the value of chas_xt_bbkz.LRR_XM
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getLrrXm() {
        return lrrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.LRR_XM
     *
     * @param lrrXm the value for chas_xt_bbkz.LRR_XM
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setLrrXm(String lrrXm) {
        this.lrrXm = lrrXm == null ? null : lrrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.XGR_SFZH
     *
     * @return the value of chas_xt_bbkz.XGR_SFZH
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.XGR_SFZH
     *
     * @param xgrSfzh the value for chas_xt_bbkz.XGR_SFZH
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.XGSJ
     *
     * @return the value of chas_xt_bbkz.XGSJ
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.XGSJ
     *
     * @param xgsj the value for chas_xt_bbkz.XGSJ
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.XGR_XM
     *
     * @return the value of chas_xt_bbkz.XGR_XM
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getXgrXm() {
        return xgrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.XGR_XM
     *
     * @param xgrXm the value for chas_xt_bbkz.XGR_XM
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setXgrXm(String xgrXm) {
        this.xgrXm = xgrXm == null ? null : xgrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.ISDEL
     *
     * @return the value of chas_xt_bbkz.ISDEL
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.ISDEL
     *
     * @param isdel the value for chas_xt_bbkz.ISDEL
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.CLIENT_NO
     *
     * @return the value of chas_xt_bbkz.CLIENT_NO
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getClientNo() {
        return clientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.CLIENT_NO
     *
     * @param clientNo the value for chas_xt_bbkz.CLIENT_NO
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setClientNo(String clientNo) {
        this.clientNo = clientNo == null ? null : clientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.CLIENT_TYPE
     *
     * @return the value of chas_xt_bbkz.CLIENT_TYPE
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.CLIENT_TYPE
     *
     * @param clientType the value for chas_xt_bbkz.CLIENT_TYPE
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.INSTALL_ID
     *
     * @return the value of chas_xt_bbkz.INSTALL_ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getInstallId() {
        return installId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.INSTALL_ID
     *
     * @param installId the value for chas_xt_bbkz.INSTALL_ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setInstallId(String installId) {
        this.installId = installId == null ? null : installId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.UPDATE_ID
     *
     * @return the value of chas_xt_bbkz.UPDATE_ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.UPDATE_ID
     *
     * @param updateId the value for chas_xt_bbkz.UPDATE_ID
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.RECENT
     *
     * @return the value of chas_xt_bbkz.RECENT
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public Integer getRecent() {
        return recent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.RECENT
     *
     * @param recent the value for chas_xt_bbkz.RECENT
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setRecent(Integer recent) {
        this.recent = recent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.EXPLAIN
     *
     * @return the value of chas_xt_bbkz.EXPLAIN
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.EXPLAIN
     *
     * @param explain the value for chas_xt_bbkz.EXPLAIN
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_bbkz.DATA_FLAG
     *
     * @return the value of chas_xt_bbkz.DATA_FLAG
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_bbkz.DATA_FLAG
     *
     * @param dataFlag the value for chas_xt_bbkz.DATA_FLAG
     *
     * @mbg.generated Mon Sep 03 17:54:40 CST 2018
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }
}