package com.wckj.chasstage.modules.sign.entity;

import java.util.Date;

public class ChasSign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.id
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.isdel
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private Integer isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.data_flag
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String dataFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.lrr_sfzh
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String lrrSfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.lrsj
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private Date lrsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.xgr_sfzh
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String xgrSfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.xgsj
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private Date xgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.rybh
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String rybh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.ryxm
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String ryxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.zbdw_bh
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String zbdwBh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.sign_type
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.sign_name
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String signName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_xt_sign.img_body
     *
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    private String imgBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.id
     *
     * @return the value of chas_xt_sign.id
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.id
     *
     * @param id the value for chas_xt_sign.id
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.isdel
     *
     * @return the value of chas_xt_sign.isdel
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.isdel
     *
     * @param isdel the value for chas_xt_sign.isdel
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.data_flag
     *
     * @return the value of chas_xt_sign.data_flag
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.data_flag
     *
     * @param dataFlag the value for chas_xt_sign.data_flag
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.lrr_sfzh
     *
     * @return the value of chas_xt_sign.lrr_sfzh
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.lrr_sfzh
     *
     * @param lrrSfzh the value for chas_xt_sign.lrr_sfzh
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.lrsj
     *
     * @return the value of chas_xt_sign.lrsj
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.lrsj
     *
     * @param lrsj the value for chas_xt_sign.lrsj
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.xgr_sfzh
     *
     * @return the value of chas_xt_sign.xgr_sfzh
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.xgr_sfzh
     *
     * @param xgrSfzh the value for chas_xt_sign.xgr_sfzh
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.xgsj
     *
     * @return the value of chas_xt_sign.xgsj
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.xgsj
     *
     * @param xgsj the value for chas_xt_sign.xgsj
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.rybh
     *
     * @return the value of chas_xt_sign.rybh
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getRybh() {
        return rybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.rybh
     *
     * @param rybh the value for chas_xt_sign.rybh
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setRybh(String rybh) {
        this.rybh = rybh == null ? null : rybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.ryxm
     *
     * @return the value of chas_xt_sign.ryxm
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getRyxm() {
        return ryxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.ryxm
     *
     * @param ryxm the value for chas_xt_sign.ryxm
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setRyxm(String ryxm) {
        this.ryxm = ryxm == null ? null : ryxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.zbdw_bh
     *
     * @return the value of chas_xt_sign.zbdw_bh
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getZbdwBh() {
        return zbdwBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.zbdw_bh
     *
     * @param zbdwBh the value for chas_xt_sign.zbdw_bh
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setZbdwBh(String zbdwBh) {
        this.zbdwBh = zbdwBh == null ? null : zbdwBh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.sign_type
     *
     * @return the value of chas_xt_sign.sign_type
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.sign_type
     *
     * @param signType the value for chas_xt_sign.sign_type
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.sign_name
     *
     * @return the value of chas_xt_sign.sign_name
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getSignName() {
        return signName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.sign_name
     *
     * @param signName the value for chas_xt_sign.sign_name
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setSignName(String signName) {
        this.signName = signName == null ? null : signName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_xt_sign.img_body
     *
     * @return the value of chas_xt_sign.img_body
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public String getImgBody() {
        return imgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_xt_sign.img_body
     *
     * @param imgBody the value for chas_xt_sign.img_body
     * @mbg.generated Wed Jul 18 15:05:50 CST 2018
     */
    public void setImgBody(String imgBody) {
        this.imgBody = imgBody == null ? null : imgBody.trim();
    }
}