package com.wckj.chasstage.modules.cssp.entity;

import java.util.Date;

public class ChasYmCssp implements java.io.Serializable{
    /**
     * 
     */
    private static final long serialVersionUID = 7109415823940290831L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.ID
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.ISDEL
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.dataflag
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String dataflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.LRR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.LRSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.XGR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.XGSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.baqid
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String baqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.BAQMC
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String baqmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.YWBH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String ywbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.RYBH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String rybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.RYXM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String ryxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.LKYY
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String lkyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.LKSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private Date lksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.HLSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private Date hlsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.SPR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String sprSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.SPR_XM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String sprXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.ZBDW_BH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String zbdwBh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.ZBDW_MC
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String zbdwMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.ZBR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String zbrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.ZBR_XM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String zbrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.SPZT
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String spzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.SPYJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String spyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.SPSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private Date spsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.RYZT
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String ryzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.LKYYDM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String lkyydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_cssp.LKLX
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    private String lklx;
    
    private String cslx;

    private String dwxtbh;
    
    public ChasYmCssp(){
        this.isdel=0;
        this.dataflag="0";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.ID
     *
     * @return the value of chas_yw_cssp.ID
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.ID
     *
     * @param id the value for chas_yw_cssp.ID
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.ISDEL
     *
     * @return the value of chas_yw_cssp.ISDEL
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.ISDEL
     *
     * @param isdel the value for chas_yw_cssp.ISDEL
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.dataflag
     *
     * @return the value of chas_yw_cssp.dataflag
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getDataflag() {
        return dataflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.dataflag
     *
     * @param dataflag the value for chas_yw_cssp.dataflag
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setDataflag(String dataflag) {
        this.dataflag = dataflag == null ? null : dataflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.LRR_SFZH
     *
     * @return the value of chas_yw_cssp.LRR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.LRR_SFZH
     *
     * @param lrrSfzh the value for chas_yw_cssp.LRR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.LRSJ
     *
     * @return the value of chas_yw_cssp.LRSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.LRSJ
     *
     * @param lrsj the value for chas_yw_cssp.LRSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.XGR_SFZH
     *
     * @return the value of chas_yw_cssp.XGR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.XGR_SFZH
     *
     * @param xgrSfzh the value for chas_yw_cssp.XGR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.XGSJ
     *
     * @return the value of chas_yw_cssp.XGSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.XGSJ
     *
     * @param xgsj the value for chas_yw_cssp.XGSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.baqid
     *
     * @return the value of chas_yw_cssp.baqid
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getBaqid() {
        return baqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.baqid
     *
     * @param baqid the value for chas_yw_cssp.baqid
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setBaqid(String baqid) {
        this.baqid = baqid == null ? null : baqid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.BAQMC
     *
     * @return the value of chas_yw_cssp.BAQMC
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getBaqmc() {
        return baqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.BAQMC
     *
     * @param baqmc the value for chas_yw_cssp.BAQMC
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setBaqmc(String baqmc) {
        this.baqmc = baqmc == null ? null : baqmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.YWBH
     *
     * @return the value of chas_yw_cssp.YWBH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getYwbh() {
        return ywbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.YWBH
     *
     * @param ywbh the value for chas_yw_cssp.YWBH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setYwbh(String ywbh) {
        this.ywbh = ywbh == null ? null : ywbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.RYBH
     *
     * @return the value of chas_yw_cssp.RYBH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getRybh() {
        return rybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.RYBH
     *
     * @param rybh the value for chas_yw_cssp.RYBH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setRybh(String rybh) {
        this.rybh = rybh == null ? null : rybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.RYXM
     *
     * @return the value of chas_yw_cssp.RYXM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getRyxm() {
        return ryxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.RYXM
     *
     * @param ryxm the value for chas_yw_cssp.RYXM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setRyxm(String ryxm) {
        this.ryxm = ryxm == null ? null : ryxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.LKYY
     *
     * @return the value of chas_yw_cssp.LKYY
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getLkyy() {
        return lkyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.LKYY
     *
     * @param lkyy the value for chas_yw_cssp.LKYY
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setLkyy(String lkyy) {
        this.lkyy = lkyy == null ? null : lkyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.LKSJ
     *
     * @return the value of chas_yw_cssp.LKSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public Date getLksj() {
        return lksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.LKSJ
     *
     * @param lksj the value for chas_yw_cssp.LKSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setLksj(Date lksj) {
        this.lksj = lksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.HLSJ
     *
     * @return the value of chas_yw_cssp.HLSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public Date getHlsj() {
        return hlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.HLSJ
     *
     * @param hlsj the value for chas_yw_cssp.HLSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setHlsj(Date hlsj) {
        this.hlsj = hlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.SPR_SFZH
     *
     * @return the value of chas_yw_cssp.SPR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getSprSfzh() {
        return sprSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.SPR_SFZH
     *
     * @param sprSfzh the value for chas_yw_cssp.SPR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setSprSfzh(String sprSfzh) {
        this.sprSfzh = sprSfzh == null ? null : sprSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.SPR_XM
     *
     * @return the value of chas_yw_cssp.SPR_XM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getSprXm() {
        return sprXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.SPR_XM
     *
     * @param sprXm the value for chas_yw_cssp.SPR_XM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setSprXm(String sprXm) {
        this.sprXm = sprXm == null ? null : sprXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.ZBDW_BH
     *
     * @return the value of chas_yw_cssp.ZBDW_BH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getZbdwBh() {
        return zbdwBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.ZBDW_BH
     *
     * @param zbdwBh the value for chas_yw_cssp.ZBDW_BH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setZbdwBh(String zbdwBh) {
        this.zbdwBh = zbdwBh == null ? null : zbdwBh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.ZBDW_MC
     *
     * @return the value of chas_yw_cssp.ZBDW_MC
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getZbdwMc() {
        return zbdwMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.ZBDW_MC
     *
     * @param zbdwMc the value for chas_yw_cssp.ZBDW_MC
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setZbdwMc(String zbdwMc) {
        this.zbdwMc = zbdwMc == null ? null : zbdwMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.ZBR_SFZH
     *
     * @return the value of chas_yw_cssp.ZBR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getZbrSfzh() {
        return zbrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.ZBR_SFZH
     *
     * @param zbrSfzh the value for chas_yw_cssp.ZBR_SFZH
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setZbrSfzh(String zbrSfzh) {
        this.zbrSfzh = zbrSfzh == null ? null : zbrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.ZBR_XM
     *
     * @return the value of chas_yw_cssp.ZBR_XM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getZbrXm() {
        return zbrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.ZBR_XM
     *
     * @param zbrXm the value for chas_yw_cssp.ZBR_XM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setZbrXm(String zbrXm) {
        this.zbrXm = zbrXm == null ? null : zbrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.SPZT
     *
     * @return the value of chas_yw_cssp.SPZT
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getSpzt() {
        return spzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.SPZT
     *
     * @param spzt the value for chas_yw_cssp.SPZT
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setSpzt(String spzt) {
        this.spzt = spzt == null ? null : spzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.SPYJ
     *
     * @return the value of chas_yw_cssp.SPYJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getSpyj() {
        return spyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.SPYJ
     *
     * @param spyj the value for chas_yw_cssp.SPYJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setSpyj(String spyj) {
        this.spyj = spyj == null ? null : spyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.SPSJ
     *
     * @return the value of chas_yw_cssp.SPSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public Date getSpsj() {
        return spsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.SPSJ
     *
     * @param spsj the value for chas_yw_cssp.SPSJ
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setSpsj(Date spsj) {
        this.spsj = spsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.RYZT
     *
     * @return the value of chas_yw_cssp.RYZT
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getRyzt() {
        return ryzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.RYZT
     *
     * @param ryzt the value for chas_yw_cssp.RYZT
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setRyzt(String ryzt) {
        this.ryzt = ryzt == null ? null : ryzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.LKYYDM
     *
     * @return the value of chas_yw_cssp.LKYYDM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getLkyydm() {
        return lkyydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.LKYYDM
     *
     * @param lkyydm the value for chas_yw_cssp.LKYYDM
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setLkyydm(String lkyydm) {
        this.lkyydm = lkyydm == null ? null : lkyydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_cssp.LKLX
     *
     * @return the value of chas_yw_cssp.LKLX
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public String getLklx() {
        return lklx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_cssp.LKLX
     *
     * @param lklx the value for chas_yw_cssp.LKLX
     *
     * @mbg.generated Tue Nov 21 16:41:21 CST 2017
     */
    public void setLklx(String lklx) {
        this.lklx = lklx == null ? null : lklx.trim();
    }

    public String getCslx() {
        return cslx;
    }

    public void setCslx(String cslx) {
        this.cslx = cslx;
    }

    public String getDwxtbh() {
        return dwxtbh;
    }

    public void setDwxtbh(String dwxtbh) {
        this.dwxtbh = dwxtbh;
    }
}