package com.wckj.chasstage.modules.yybb.entity;

import java.util.Date;

public class ChasYwYybb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.id
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.baqid
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private String baqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.bbhj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private String bbhj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.bbnr
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private String bbnr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.lrsj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private Date lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.xgsj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.isdel
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.baqmc
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private String baqmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.sfqy
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private Integer sfqy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.qyid
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private String qyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chas_yw_yybb.qymc
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    private String qymc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.id
     *
     * @return the value of chas_yw_yybb.id
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.id
     *
     * @param id the value for chas_yw_yybb.id
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.baqid
     *
     * @return the value of chas_yw_yybb.baqid
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public String getBaqid() {
        return baqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.baqid
     *
     * @param baqid the value for chas_yw_yybb.baqid
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setBaqid(String baqid) {
        this.baqid = baqid == null ? null : baqid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.bbhj
     *
     * @return the value of chas_yw_yybb.bbhj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public String getBbhj() {
        return bbhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.bbhj
     *
     * @param bbhj the value for chas_yw_yybb.bbhj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setBbhj(String bbhj) {
        this.bbhj = bbhj == null ? null : bbhj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.bbnr
     *
     * @return the value of chas_yw_yybb.bbnr
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public String getBbnr() {
        return bbnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.bbnr
     *
     * @param bbnr the value for chas_yw_yybb.bbnr
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setBbnr(String bbnr) {
        this.bbnr = bbnr == null ? null : bbnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.lrsj
     *
     * @return the value of chas_yw_yybb.lrsj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.lrsj
     *
     * @param lrsj the value for chas_yw_yybb.lrsj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.xgsj
     *
     * @return the value of chas_yw_yybb.xgsj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.xgsj
     *
     * @param xgsj the value for chas_yw_yybb.xgsj
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.isdel
     *
     * @return the value of chas_yw_yybb.isdel
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.isdel
     *
     * @param isdel the value for chas_yw_yybb.isdel
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.baqmc
     *
     * @return the value of chas_yw_yybb.baqmc
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public String getBaqmc() {
        return baqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.baqmc
     *
     * @param baqmc the value for chas_yw_yybb.baqmc
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setBaqmc(String baqmc) {
        this.baqmc = baqmc == null ? null : baqmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.sfqy
     *
     * @return the value of chas_yw_yybb.sfqy
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public Integer getSfqy() {
        return sfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.sfqy
     *
     * @param sfqy the value for chas_yw_yybb.sfqy
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setSfqy(Integer sfqy) {
        this.sfqy = sfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.qyid
     *
     * @return the value of chas_yw_yybb.qyid
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public String getQyid() {
        return qyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.qyid
     *
     * @param qyid the value for chas_yw_yybb.qyid
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setQyid(String qyid) {
        this.qyid = qyid == null ? null : qyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chas_yw_yybb.qymc
     *
     * @return the value of chas_yw_yybb.qymc
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public String getQymc() {
        return qymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chas_yw_yybb.qymc
     *
     * @param qymc the value for chas_yw_yybb.qymc
     *
     * @mbg.generated Tue Dec 22 19:20:50 CST 2020
     */
    public void setQymc(String qymc) {
        this.qymc = qymc == null ? null : qymc.trim();
    }
}
